# Generated by Django 3.2.1 on 2021-07-12 08:08

import apps.games.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Очки')),
                ('tic_tac_toe_points', models.IntegerField(default=0, verbose_name='Очки крестики-нолики')),
                ('codenames_points', models.IntegerField(default=0, verbose_name='Очки коднеймса')),
                ('roulette_points', models.IntegerField(default=500, verbose_name='Очки рулетки')),
                ('roulette_points_today', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения очков')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.users', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='TicTacToeSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=apps.games.models.get_default_board, verbose_name='Поле')),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_tictactoesessions', to='bot.users', verbose_name='Следующий шаг')),
                ('user1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1_tictactoesessions', to='bot.users', verbose_name='Пользователь *')),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2_tictactoesessions', to='bot.users', verbose_name='Пользователь o')),
            ],
            options={
                'verbose_name': 'Крестики-нолики сессия',
                'verbose_name_plural': 'Крестики-нолики сессии',
                'ordering': ['-next_step'],
            },
        ),
        migrations.CreateModel(
            name='RouletteRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_on', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Ставка')),
                ('rate', models.IntegerField(verbose_name='Размер ставки')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chat', verbose_name='Чат')),
                ('gamer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.gamer', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Ставка рулеток',
                'verbose_name_plural': 'Ставки рулеток',
                'ordering': ['chat'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(verbose_name='Ставка')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('random', models.BooleanField(default=False, verbose_name='Случайная')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chat', verbose_name='Чат')),
                ('gamer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.gamer', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ставка',
                'verbose_name_plural': 'Ставки',
                'ordering': ['chat', 'date'],
            },
        ),
        migrations.CreateModel(
            name='PetrovichUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0, verbose_name='Побед в Петровиче')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chat', verbose_name='Чат')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Петрович игрок',
                'verbose_name_plural': 'Петрович игроки',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='PetrovichGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chat', verbose_name='Чат')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Петровича игра',
                'verbose_name_plural': 'Петрович игры',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CodenamesUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(blank=True, choices=[('blue', 'Синие'), ('red', 'Красные')], max_length=4, null=True, verbose_name='Команда')),
                ('role', models.CharField(blank=True, choices=[('captain', 'Капитан'), ('player', 'Игрок')], default='player', max_length=7, null=True, verbose_name='Роль')),
                ('role_preference', models.CharField(blank=True, choices=[('captain', 'Капитан'), ('player', 'Игрок')], default=None, max_length=7, null=True, verbose_name='Предпочтения(роль)')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chat', verbose_name='Чат')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Коднеймс игрок',
                'verbose_name_plural': 'Коднеймс игроки',
                'ordering': ['chat'],
            },
        ),
        migrations.CreateModel(
            name='CodenamesSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_step', models.CharField(blank=True, choices=[('red', 'Синие'), ('blue', 'Красные'), ('blue_wait', 'Капитан синих'), ('red_wait', 'Капитан красных')], default='blue_wait', max_length=10, null=True, verbose_name='Следующий шаг')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='Загадано слов')),
                ('word', models.CharField(blank=True, max_length=20, null=True, verbose_name='Загаданное слово')),
                ('board', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Поле')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Коднеймс сессия',
                'verbose_name_plural': 'Коднеймс сессии',
                'ordering': ['chat'],
            },
        ),
    ]
