# Generated by Django 5.1.6 on 2025-05-10 21:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetrovichGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('chat',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chat',
                                   verbose_name='Чат')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.profile',
                                              verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Петровича игра',
                'verbose_name_plural': 'Петрович игры',
            },
        ),
        migrations.CreateModel(
            name='PetrovichUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('chat',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chat',
                                   verbose_name='Чат')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.profile',
                                              verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Петрович игрок',
                'verbose_name_plural': 'Петрович игроки',
            },
        ),
        migrations.CreateModel(
            name='Wordle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('word', models.CharField(max_length=5)),
                ('steps', models.PositiveIntegerField(default=0, verbose_name='Количество попыток')),
                ('hypotheses', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=5, verbose_name='Гипотеза'), max_length=6, size=None,
                    verbose_name='Гипотезы')),
                ('message_id', models.IntegerField(blank=True, default=0, verbose_name='id первого сообщения')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chat',
                                           verbose_name='Чат')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.profile',
                                              verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия "Wordle"',
                'verbose_name_plural': 'Сессии "Wordle"',
            },
        ),
    ]
