# Generated by Django 3.0.8 on 2020-07-28 14:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

import apps.games.models


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codenamessession',
            name='board',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='rouletterate',
            name='rate',
            field=models.IntegerField(verbose_name='Размер ставки'),
        ),
        migrations.AlterField(
            model_name='rouletterate',
            name='rate_on',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='tictactoesession',
            name='board',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True,
                                                                 default=apps.games.models.get_default_board,
                                                                 verbose_name='Вложения'),
        ),
    ]
