# Generated by Django 5.0.2 on 2024-03-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0002_gamer_quiz_correct_answer_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='quiz_correct_answer_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество правильных ответов квиза'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='quiz_wrong_answer_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество неправильных ответов квиза'),
        ),
    ]
