# Generated by Django 3.1.8 on 2021-08-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210820_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Очки ставок'),
        ),
    ]
