# Generated by Django 3.0.8 on 2020-07-28 14:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import apps.games.models


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0002_auto_20200728_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoesession',
            name='board',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True,
                                                                 default=apps.games.models.get_default_board,
                                                                 verbose_name='Поле'),
        ),
    ]
