# Generated by Django 5.0 on 2024-01-28 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0003_alter_gamer_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='profile',
        ),
    ]
