# Generated by Django 5.0.4 on 2024-05-26 07:41

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0003_alter_gamer_quiz_correct_answer_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bullsandcowssession',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 550989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='bullsandcowssession',
            name='updated_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 551110, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='gamer',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 550989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='gamer',
            name='updated_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 551110, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='petrovichgames',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 550989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='petrovichgames',
            name='updated_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 551110, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='petrovichuser',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 550989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='petrovichuser',
            name='updated_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 551110, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='rate',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 550989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='rate',
            name='updated_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 551110, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='rouletterate',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 550989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='rouletterate',
            name='updated_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 551110, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='wordle',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 550989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='wordle',
            name='updated_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 551110, tzinfo=datetime.timezone.utc)),
        ),
    ]
