# Generated by Django 3.1.12 on 2021-08-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210820_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rouletterate',
            name='rate_on',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ставка'),
        ),
    ]
