# Generated by Django 3.2.7 on 2021-09-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_chat_recognize_voice'),
        ('games', '0004_auto_20210820_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='BullsAndCowsSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Загаданное число')),
                ('steps', models.PositiveIntegerField(default=1, verbose_name='Количество попыток')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.users', verbose_name='Пользователь')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chat', verbose_name='Чат')),
            ],
        ),
    ]
