# Generated by Django 3.2.7 on 2021-11-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_bullsandcowssession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamer',
            options={'ordering': ['profile'], 'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='petrovichuser',
            options={'ordering': ['profile'], 'verbose_name': 'Петрович игрок', 'verbose_name_plural': 'Петрович игроки'},
        ),
        migrations.RenameField(
            model_name='gamer',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='petrovichgames',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='petrovichuser',
            old_name='user',
            new_name='profile',
        ),
    ]
