# Generated by Django 5.0.4 on 2024-05-26 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0014_alter_bot_created_at_alter_bot_updated_at_and_more'),
        ('games', '0005_alter_bullsandcowssession_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetrovichGames',
            new_name='PetrovichGame',
        ),
    ]
