# Generated by Django 3.2.7 on 2021-11-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20211105_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bullsandcowssession',
            options={'ordering': ['chat'], 'verbose_name': 'Сессия "Быки и коровы"', 'verbose_name_plural': 'Сессии "Быки и коровы"'},
        ),
        migrations.RenameField(
            model_name='bullsandcowssession',
            old_name='author',
            new_name='profile',
        ),
    ]
