# Generated by Django 5.0.4 on 2024-05-26 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0006_rename_petrovichgames_petrovichgame'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bullsandcowssession',
            options={'verbose_name': 'Сессия "Быки и коровы"', 'verbose_name_plural': 'Сессии "Быки и коровы"'},
        ),
        migrations.AlterModelOptions(
            name='gamer',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='petrovichgame',
            options={'verbose_name': 'Петровича игра', 'verbose_name_plural': 'Петрович игры'},
        ),
        migrations.AlterModelOptions(
            name='petrovichuser',
            options={'verbose_name': 'Петрович игрок', 'verbose_name_plural': 'Петрович игроки'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'Ставка', 'verbose_name_plural': 'Ставки'},
        ),
        migrations.AlterModelOptions(
            name='wordle',
            options={'verbose_name': 'Сессия "Wordle"', 'verbose_name_plural': 'Сессии "Wordle"'},
        ),
        migrations.RemoveField(
            model_name='petrovichgame',
            name='date',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='date',
        ),
    ]
