# Generated by Django 3.2.9 on 2022-01-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20211105_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petrovichuser',
            name='wins',
        ),
    ]
