# Generated by Django 5.0.7 on 2024-07-15 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0007_alter_bullsandcowssession_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='gamer',
        ),
        migrations.RemoveField(
            model_name='rouletterate',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='rouletterate',
            name='gamer',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='bk_points',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='points',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='quiz_correct_answer_count',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='quiz_wrong_answer_count',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='roulette_points',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='roulette_points_today',
        ),
        migrations.DeleteModel(
            name='BullsAndCowsSession',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.DeleteModel(
            name='RouletteRate',
        ),
    ]
