# Generated by Django 3.2.13 on 2022-06-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0008_remove_petrovichuser_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='bullsandcowssession',
            name='message_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='id первого сообщения'),
        ),
    ]
