# Generated by Django 3.2.13 on 2022-06-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0009_bullsandcowssession_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bullsandcowssession',
            name='message_body',
            field=models.TextField(blank=True, verbose_name='Тело сообщения для игры в одном сообщении'),
        ),
    ]
