# Generated by Django 3.2.13 on 2022-11-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0011_wordle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordle',
            name='steps',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество попыток'),
        ),
    ]
