# Generated by Django 3.2.13 on 2022-11-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0012_alter_wordle_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordle',
            name='message_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='id первого сообщения'),
        ),
    ]
