# Generated by Django 3.2.13 on 2022-11-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0013_wordle_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='bk_points',
            field=models.IntegerField(default=0, verbose_name='Очки быки и коровы'),
        ),
        migrations.AddField(
            model_name='gamer',
            name='wordle_points',
            field=models.IntegerField(default=0, verbose_name='Очки Wordle'),
        ),
    ]
