[tool.poetry]
name = "petrovich"
version = "0.1.0"
description = "Чат-бот"
authors = ["AndrewSha <Xoma163rus@gmail.com>"]
readme = "README.md"
repository = "https://github.com/Xoma163/petrovich"
package-mode = false
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
beautifulsoup4 = "^4.12.3"
colorlog = "^6.8.2"
crontab = "^1.0.1"
Django = "^5.0.6"
django-environ = "^0.11.2"
django-extensions = "^3.2.3"
django-redis = "^5.4.0"
gspread = "^6.1.2"
lxml = "^5.2.2"
oauth2client = "^4.1.3"
pillow = "^10.3.0"
psycopg2 = "^2.9.9"
pydub = "^0.25.1"
python-json-logger = "^2.0.7"
requests = "^2.32.2"
transliterate = "^1.10.2"
twitch-dl = "^2.3.1"
uWSGI = "^2.0.25"
virtualenv = "^20.26.2"
wakeonlan = "^3.1.0"
xmltodict = "^0.13.0"
yandex-music = "^2.2.0"
yt-dlp = "^2024.4.9"
spotipy = "^2.23.0"
numpy = "^1.26.4"
python-dateutil = "^2.9.0.post0"
selenium = "^4.22.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
