# Generated by Django 3.2.20 on 2023-10-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorproduct',
            name='uom',
            field=models.CharField(
                choices=[('kg', 'кг'), ('g', 'г'), ('piece', 'шт'), ('jar', 'б'), ('packing', 'уп'), ('liter', 'л')],
                default='piece', max_length=10, verbose_name='Единица измерения'),
        ),
    ]
