# Generated by Django 3.2.23 on 2023-12-16 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0002_alter_calculatorproduct_uom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatorsession',
            name='products',
        ),
        migrations.RemoveField(
            model_name='calculatorsession',
            name='users',
        ),
        migrations.DeleteModel(
            name='CalculatorProduct',
        ),
        migrations.DeleteModel(
            name='CalculatorSession',
        ),
        migrations.DeleteModel(
            name='CalculatorUser',
        ),
    ]
