# Generated by Django 3.0.8 on 2021-01-07 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0002_delete_redirecturl'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('uom', models.CharField(choices=[('kg', 'кг'), ('g', 'г'), ('piece', 'шт'), ('jar', 'б'), ('packing', 'уп'), ('liter', 'л')], default='piece', max_length=10, verbose_name='Единица измерения')),
                ('is_bought', models.BooleanField(default=False, verbose_name='Куплено')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='CalculatorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='CalculatorSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('products', models.ManyToManyField(to='web.CalculatorProduct')),
                ('users', models.ManyToManyField(to='web.CalculatorUser')),
            ],
        ),
        migrations.AddField(
            model_name='calculatorproduct',
            name='bought_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.CalculatorUser'),
        ),
    ]
