# Generated by Django 3.0.8 on 2021-01-07 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210107_0517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculatorproduct',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='calculatorsession',
            options={'verbose_name': 'сессия', 'verbose_name_plural': 'сессии'},
        ),
        migrations.AlterModelOptions(
            name='calculatoruser',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
