# Generated by Django 3.0.8 on 2021-01-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210107_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorsession',
            name='products',
            field=models.ManyToManyField(to='web.CalculatorProduct', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='calculatorsession',
            name='users',
            field=models.ManyToManyField(to='web.CalculatorUser', verbose_name='Пользователи'),
        ),
    ]
