# Generated by Django 3.0.8 on 2021-01-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210107_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorsession',
            name='products',
            field=models.ManyToManyField(blank=True, to='web.CalculatorProduct', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='calculatorsession',
            name='users',
            field=models.ManyToManyField(blank=True, to='web.CalculatorUser', verbose_name='Пользователи'),
        ),
    ]
