# Generated by Django 3.0.8 on 2021-01-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210108_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculatoruser',
            options={'ordering': ['name'], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='calculatorproduct',
            name='count',
            field=models.PositiveIntegerField(blank=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='calculatorproduct',
            name='name',
            field=models.CharField(blank=True, max_length=127, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='calculatorproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
