# Generated by Django 5.2.9 on 2026-01-24 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата напоминания')),
                ('crontab', models.CharField(blank=True, max_length=100, null=True, verbose_name='Crontab')),
                ('text', models.CharField(blank=True, default='', max_length=1000, verbose_name='Текст/команда')),
                ('mention_sender', models.BooleanField(default=True, verbose_name='Упоминать автора')),
                ('attachments', models.JSONField(blank=True, default=dict, verbose_name='Вложения')),
                ('message_thread_id',
                 models.IntegerField(blank=True, default=None, null=True, verbose_name='message_thread_id')),
                ('chat',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chat',
                                   verbose_name='Чат')),
                ('user',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.user',
                                   verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'напоминание',
                'verbose_name_plural': 'напоминания',
            },
        ),
    ]
