# Generated by Django 5.2.9 on 2026-01-24 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0006_alter_profile_city'),
        ('notifies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chat',
                                    verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='notify',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.user',
                                    verbose_name='Пользователь'),
        ),
    ]
