# Generated by Django 5.2.9 on 2026-01-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('channel_id', models.CharField(max_length=100, verbose_name='ID канала')),
                ('video_id', models.CharField(max_length=100, null=True, verbose_name='ID видео')),
                ('filename', models.CharField(max_length=1024, verbose_name='Название файла')),
                ('video',
                 models.FileField(blank=True, max_length=1024, upload_to='service/video/', verbose_name='Видео')),
                ('original_url',
                 models.URLField(blank=True, max_length=1024, verbose_name='Ссылка на оригинальное видео')),
            ],
            options={
                'verbose_name': 'Кэш видео',
                'verbose_name_plural': 'Кэши видео',
                'unique_together': {('channel_id', 'video_id')},
            },
        ),
    ]
