# Generated by Django 5.2.9 on 2026-01-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('media_command', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocache',
            name='original_url',
        ),
        migrations.AddField(
            model_name='videocache',
            name='source_url',
            field=models.URLField(blank=True, max_length=1024, verbose_name='Ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='videocache',
            name='video',
            field=models.FileField(blank=True, max_length=1024, upload_to='commands/media_command/video/',
                                   verbose_name='Видео'),
        ),
    ]
