# Generated by Django 6.0.2 on 2026-03-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(choices=[('chatgpt', 'CHATGPT'), ('grok', 'GROK'), ('qwen', 'QWEN')], max_length=32,
                                   unique=True, verbose_name='Провайдер'),
        ),
    ]
