# Generated by Django 6.0.2 on 2026-03-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0002_alter_provider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptpreset',
            name='use_stream',
            field=models.BooleanField(null=True, verbose_name='Использовать режим потокового вывода'),
        ),
        migrations.AddField(
            model_name='profilegptsettings',
            name='use_stream',
            field=models.BooleanField(null=True, verbose_name='Использовать режим потокового вывода'),
        ),
    ]
