# Generated by Django 6.0.2 on 2026-03-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0003_gptpreset_use_stream_profilegptsettings_use_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptpreset',
            name='gpt_5_settings_reasoning_effort_level',
            field=models.CharField(blank=True,
                                   choices=[('xhigh', 'XHIGH'), ('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW'),
                                            ('minimal', 'MINIMAL'), ('none', 'NONE')], max_length=32, null=True,
                                   verbose_name='Уровень рассуждений моделей семейства gpt-5'),
        ),
        migrations.AlterField(
            model_name='profilegptsettings',
            name='gpt_5_settings_reasoning_effort_level',
            field=models.CharField(blank=True,
                                   choices=[('xhigh', 'XHIGH'), ('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW'),
                                            ('minimal', 'MINIMAL'), ('none', 'NONE')], max_length=32, null=True,
                                   verbose_name='Уровень рассуждений моделей семейства gpt-5'),
        ),
    ]
