# Generated by Django 5.2.4 on 2025-09-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0003_profilegptsettings_gpt_5_settings_reasoning_effort_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilegptpreset',
            name='gpt_5_settings_reasoning_effort_level',
            field=models.CharField(blank=True, choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW'),
                                                        ('minimal', 'MINIMAL')], max_length=32, null=True,
                                   verbose_name='Уровень рассуждений моделей семейства gpt-5'),
        ),
        migrations.AlterField(
            model_name='profilegptpreset',
            name='gpt_5_settings_verbosity_level',
            field=models.CharField(blank=True, choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')],
                                   max_length=32, null=True,
                                   verbose_name='Уровень многословности моделей семейства gpt-5'),
        ),
        migrations.AlterField(
            model_name='profilegptsettings',
            name='gpt_5_settings_reasoning_effort_level',
            field=models.CharField(blank=True, choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW'),
                                                        ('minimal', 'MINIMAL')], max_length=32, null=True,
                                   verbose_name='Уровень рассуждений моделей семейства gpt-5'),
        ),
        migrations.AlterField(
            model_name='profilegptsettings',
            name='gpt_5_settings_verbosity_level',
            field=models.CharField(blank=True, choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')],
                                   max_length=32, null=True,
                                   verbose_name='Уровень многословности моделей семейства gpt-5'),
        ),
    ]
