# Generated by Django 6.0.3 on 2026-09-14 15:35

from django.db import migrations, models


def consolidate_image_draw_models(apps, schema_editor):
    ImageDrawModel = apps.get_model("gpt", "ImageDrawModel")
    ProfileGPTSettings = apps.get_model("gpt", "ProfileGPTSettings")
    GPTPreset = apps.get_model("gpt", "GPTPreset")

    model_groups = ImageDrawModel.objects.values_list("provider_id", "name").distinct()
    for provider_id, name in model_groups:
        variants = list(
            ImageDrawModel.objects.filter(provider_id=provider_id, name=name).order_by("-is_default", "pk")
        )
        keeper = variants[0]
        keeper.supported_qualities = list(dict.fromkeys(variant.quality for variant in variants))
        keeper.supported_sizes = list(dict.fromkeys(f"{variant.width}x{variant.height}" for variant in variants))
        keeper.save(update_fields=["supported_qualities", "supported_sizes"])

        duplicate_ids = [variant.pk for variant in variants[1:]]
        if not duplicate_ids:
            continue
        ProfileGPTSettings.objects.filter(image_draw_model_id__in=duplicate_ids).update(image_draw_model_id=keeper.pk)
        GPTPreset.objects.filter(image_draw_model_id__in=duplicate_ids).update(image_draw_model_id=keeper.pk)
        ImageDrawModel.objects.filter(pk__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0004_alter_gptpreset_gpt_5_settings_reasoning_effort_level_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imagedrawmodel',
            name='unique_name_width_height_quality_img_draw',
        ),
        migrations.AddField(
            model_name='imagedrawmodel',
            name='image_cached_input_1m_token_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Стоимость 1млн. кэшированных входных токенов изображений'),
        ),
        migrations.AddField(
            model_name='imagedrawmodel',
            name='image_input_1m_token_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Стоимость 1млн. входных токенов изображений'),
        ),
        migrations.AddField(
            model_name='imagedrawmodel',
            name='image_output_1m_token_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Стоимость 1млн. выходных токенов изображений'),
        ),
        migrations.AddField(
            model_name='imagedrawmodel',
            name='supported_qualities',
            field=models.JSONField(blank=True, default=list, verbose_name='Поддерживаемые качества'),
        ),
        migrations.AddField(
            model_name='imagedrawmodel',
            name='supported_sizes',
            field=models.JSONField(blank=True, default=list, verbose_name='Поддерживаемые размеры'),
        ),
        migrations.AddField(
            model_name='imagedrawmodel',
            name='text_cached_input_1m_token_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Стоимость 1млн. кэшированных входных текстовых токенов'),
        ),
        migrations.AddField(
            model_name='imagedrawmodel',
            name='text_input_1m_token_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Стоимость 1млн. входных текстовых токенов'),
        ),
        migrations.AlterField(
            model_name='imagedrawmodel',
            name='image_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Резервная фиксированная стоимость изображения'),
        ),
        migrations.AlterField(
            model_name='imagedrawmodel',
            name='quality',
            field=models.CharField(max_length=32, verbose_name='Качество по умолчанию'),
        ),
        migrations.RunPython(consolidate_image_draw_models, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='imagedrawmodel',
            constraint=models.UniqueConstraint(fields=('name', 'provider'), name='unique_name_provider_img_draw'),
        ),
    ]
