# Generated by Django 6.0.3 on 2026-04-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0004_alter_gptpreset_gpt_5_settings_reasoning_effort_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilegptsettings',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('api_key', 'API key'), ('oauth_device', 'OpenAI OAuth (device)')], default='', max_length=32, verbose_name='Тип авторизации'),
        ),
        migrations.AddField(
            model_name='profilegptsettings',
            name='oauth_access_token',
            field=models.TextField(blank=True, verbose_name='OAuth access token'),
        ),
        migrations.AddField(
            model_name='profilegptsettings',
            name='oauth_account_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='OAuth account id'),
        ),
        migrations.AddField(
            model_name='profilegptsettings',
            name='oauth_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OAuth token expires at'),
        ),
        migrations.AddField(
            model_name='profilegptsettings',
            name='oauth_id_token',
            field=models.TextField(blank=True, verbose_name='OAuth id token'),
        ),
        migrations.AddField(
            model_name='profilegptsettings',
            name='oauth_last_error',
            field=models.CharField(blank=True, max_length=1024, verbose_name='OAuth last error'),
        ),
        migrations.AddField(
            model_name='profilegptsettings',
            name='oauth_last_refresh_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OAuth last refresh at'),
        ),
        migrations.AddField(
            model_name='profilegptsettings',
            name='oauth_refresh_token',
            field=models.TextField(blank=True, verbose_name='OAuth refresh token'),
        ),
    ]
