# Generated by Django 5.2.4 on 2025-09-02 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0002_initial'),
        ('gpt', '0004_alter_profilegptpreset_gpt_5_settings_reasoning_effort_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('gpt_5_settings_reasoning_effort_level', models.CharField(blank=True, choices=[('high', 'HIGH'),
                                                                                                ('medium', 'MEDIUM'),
                                                                                                ('low', 'LOW'),
                                                                                                ('minimal', 'MINIMAL')],
                                                                           max_length=32, null=True,
                                                                           verbose_name='Уровень рассуждений моделей семейства gpt-5')),
                ('gpt_5_settings_verbosity_level',
                 models.CharField(blank=True, choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')],
                                  max_length=32, null=True,
                                  verbose_name='Уровень многословности моделей семейства gpt-5')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=1023, verbose_name='Описание')),
                ('preprompt_text', models.TextField(blank=True, verbose_name='Текст препромпта')),
                ('completions_model',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   to='gpt.completionsmodel', verbose_name='Модель обработки текста')),
                ('image_draw_model',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   to='gpt.imagedrawmodel', verbose_name='Модель рисования изображений')),
                ('image_edit_model',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   to='gpt.imageeditmodel', verbose_name='Модель редактирования изображений')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpt_presets',
                                              to='bot.profile', verbose_name='Профиль')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt.provider',
                                               verbose_name='Провайдер')),
                ('vision_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   to='gpt.visionmodel', verbose_name='Модель обработки изображений')),
                ('voice_recognition_model',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   to='gpt.voicerecognitionmodel', verbose_name='Модель распознования голоса')),
            ],
            options={
                'unique_together': {('profile', 'provider', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='ProfileGPTPreset',
        ),
    ]
