# Generated by Django 6.0.3 on 2026-09-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0005_normalize_image_draw_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imageeditmodel',
            name='unique_name_width_height_image_edit',
        ),
        migrations.RemoveField(
            model_name='gptpreset',
            name='image_edit_model',
        ),
        migrations.RemoveField(
            model_name='profilegptsettings',
            name='image_edit_model',
        ),
        migrations.DeleteModel(
            name='ImageEditModel',
        ),
    ]
