# Generated by Django 6.0.2 on 2026-04-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gpt", "0005_profilegptsettings_auth_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="completionsmodel",
            name="is_enabled_for_oauth",
            field=models.BooleanField(default=False, verbose_name="Доступна через OpenAI OAuth"),
        ),
    ]
