# Generated by Django 5.2.4 on 2025-09-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0006_alter_gptpreset_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gptpreset',
            options={'verbose_name': 'Пресет GPT', 'verbose_name_plural': 'Пресеты GPT'},
        ),
        migrations.AddField(
            model_name='gptpreset',
            name='gpt_5_settings_web_search',
            field=models.BooleanField(null=True, verbose_name='Поиск информации в интернете'),
        ),
        migrations.AddField(
            model_name='profilegptsettings',
            name='gpt_5_settings_web_search',
            field=models.BooleanField(null=True, verbose_name='Поиск информации в интернете'),
        ),
    ]
