# Generated by Django 5.2.4 on 2025-10-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0008_gptpreset_use_debug_profilegptsettings_use_debug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completionsmodel',
            old_name='prompt_1m_token_cost',
            new_name='input_1m_token_cost',
        ),
        migrations.RenameField(
            model_name='completionsmodel',
            old_name='completion_1m_token_cost',
            new_name='output_1m_token_cost',
        ),
        migrations.RenameField(
            model_name='visionmodel',
            old_name='prompt_1m_token_cost',
            new_name='input_1m_token_cost',
        ),
        migrations.RenameField(
            model_name='visionmodel',
            old_name='completion_1m_token_cost',
            new_name='output_1m_token_cost',
        ),
        migrations.AddField(
            model_name='completionsmodel',
            name='input_cached_1m_token_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8,
                                      verbose_name='Стоимость за 1млн. входных токенов (кэшированных)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visionmodel',
            name='input_cached_1m_token_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8,
                                      verbose_name='Стоимость за 1млн. входных токенов (кэшированных)'),
            preserve_default=False,
        ),
    ]
