# Generated by Django 5.2.4 on 2025-11-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0009_rename_prompt_1m_token_cost_completionsmodel_input_1m_token_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completionsmodel',
            name='web_search_1k_token_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8,
                                      verbose_name='Стоимость за 1тыс. поисковых токенов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visionmodel',
            name='web_search_1k_token_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8,
                                      verbose_name='Стоимость за 1тыс. поисковых токенов'),
            preserve_default=False,
        ),
    ]
