# Generated by Django 5.2.9 on 2026-01-24 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0006_alter_profile_city'),
        ('gpt', '0012_alter_provider_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completionsmodel',
            name='verbose_name',
        ),
        migrations.RemoveField(
            model_name='imagedrawmodel',
            name='verbose_name',
        ),
        migrations.RemoveField(
            model_name='imageeditmodel',
            name='verbose_name',
        ),
        migrations.RemoveField(
            model_name='visionmodel',
            name='verbose_name',
        ),
        migrations.RemoveField(
            model_name='voicerecognitionmodel',
            name='verbose_name',
        ),
        migrations.AlterField(
            model_name='preprompt',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='bot.profile', verbose_name='Профиль автора'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.profile',
                                    verbose_name='Профиль автора'),
        ),
    ]
