# Generated by Django 3.0.8 on 2020-09-13 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('bot', '0006_auto_20200728_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number',
                 models.CharField(help_text='***-* или другое', max_length=100, verbose_name='Номер кабинета')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное название пары без сокращений', max_length=200,
                                          verbose_name='Название')),
                ('short_name', models.CharField(blank=True,
                                                help_text='Сокращенное название (если оставить пустым, то сгенерируется автоматически)',
                                                max_length=50, verbose_name='Название сокращённое')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='4 цифры', verbose_name='Номер группы')),
                ('title',
                 models.CharField(blank=True, help_text='прост так', max_length=100, verbose_name='Название группы')),
                ('conference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.Chat',
                                                 verbose_name='Конфа')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Иванов И.И.', max_length=100, verbose_name='ФИО преподавателя')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.CharField(
                    choices=[('1', '1. 8:00-9:35'), ('2', '2. 9:45-11:20'), ('3', '3. 11:30-13:05'),
                             ('4', '4. 13:30-15:05'), ('5', '5. 15:15-16:50'), ('6', '6. 17:00-18:35'),
                             ('7', '7. 18:45-20:15'), ('8', '8. 20:25-21:55')], max_length=2,
                    verbose_name='Номер пары')),
                ('lesson_type', models.CharField(
                    choices=[('1', 'Лекция'), ('2', 'Практика'), ('3', 'Лабораторная работа'), ('4', 'Другое')],
                    max_length=2, verbose_name='Тип пары')),
                ('week_number', models.CharField(
                    choices=[('1', 'Лекция'), ('2', 'Практика'), ('3', 'Лабораторная работа'), ('4', 'Другое')],
                    max_length=2, verbose_name='Номер недели')),
                ('cabinet',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Cabinet',
                                   verbose_name='Кабинет')),
                ('group',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Group',
                                   verbose_name='Группа')),
                ('teacher',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Teacher',
                                   verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
            },
        ),
    ]
