# Generated by Django 3.1.8 on 2021-08-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='group',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Cabinet',
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
