# Generated by Django 3.0.8 on 2020-09-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='week_number',
            field=models.CharField(choices=[('1', '1 - нечётные'), ('2', '2 - чётные')], max_length=2,
                                   verbose_name='Номер недели'),
        ),
    ]
