# Generated by Django 3.0.8 on 2020-09-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0003_auto_20200915_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='day_of_week',
            field=models.CharField(
                choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'),
                         ('6', 'Суббота'), ('7', 'Воскресенье')], default='1', max_length=2,
                verbose_name='День недели'),
        ),
    ]
