# Generated by Django 3.0.8 on 2020-09-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0004_lesson_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(
                choices=[('1', 'Лекция'), ('2', 'Практика'), ('3', 'Лабораторная работа'), ('5', 'Курсовая'),
                         ('4', 'Другое')], max_length=2, verbose_name='Тип пары'),
        ),
    ]
