# Generated by Django 3.0.8 on 2020-09-17 17:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0009_auto_20200917_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='week_number',
            field=models.CharField(
                choices=[('3', '3'), ('2', '2'), ('8', '8'), ('0', '0'), ('12', '12'), ('4', '4'), ('1', '1'),
                         ('5', '5'), ('7', '7'), ('9', '9'), ('10', '10'), ('13', '13'), ('14', '14'), ('6', '6'),
                         ('15', '15'), ('11', '11')], max_length=2, verbose_name='Номер недели'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='week_number2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(
                choices=[('3', '3'), ('2', '2'), ('8', '8'), ('0', '0'), ('12', '12'), ('4', '4'), ('1', '1'),
                         ('5', '5'), ('7', '7'), ('9', '9'), ('10', '10'), ('13', '13'), ('14', '14'), ('6', '6'),
                         ('15', '15'), ('11', '11')], max_length=2, verbose_name='Номер недели 2'), default=list,
                                                            size=None),
        ),
    ]
