# Generated by Django 3.0.8 on 2020-09-17 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0012_auto_20200917_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='week_number2',
            new_name='week_number',
        ),
    ]
