# Generated by Django 3.0.8 on 2020-09-18 17:54

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0014_auto_20200917_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='first_lesson_day',
            field=models.DateField(default=datetime.date(2020, 9, 18),
                                   help_text='Это поле нужно чтобы точно узнавать когда начинается первая неделя',
                                   verbose_name='Дата первой даты'),
        ),
    ]
