# Generated by Django 3.0.8 on 2020-12-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_auto_20200918_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['day_of_week', 'lesson_number', 'subgroup'], 'verbose_name': 'Пара', 'verbose_name_plural': 'Пары'},
        ),
        migrations.AddField(
            model_name='discipline',
            name='bbb_link',
            field=models.TextField(blank=True, help_text='Бот будет слать этот текст когда наступит пара', verbose_name='Ссылка bbb'),
        ),
        migrations.AddField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Обновлять расписание?'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subgroup',
            field=models.CharField(choices=[('0', 'Все'), ('1', '1'), ('2', '2')], default='0', max_length=2, verbose_name='Подгруппа'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(blank=True, help_text='Бот будет менять заголовок конфы на это название группы', max_length=100, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('1', '🍏 Лекция'), ('2', '🍎 Практика'), ('3', '🍋 Лабораторная работа'), ('5', 'Курсовая'), ('4', 'Другое')], max_length=2, verbose_name='Тип пары'),
        ),
    ]
