# Generated by Django 3.0.8 on 2020-10-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0019_auto_20201022_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='bbb_link',
            field=models.URLField(blank=True),
        ),
    ]
