# Generated by Django 3.0.8 on 2020-10-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0020_discipline_bbb_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='bbb_link',
            field=models.TextField(blank=True, help_text='Бот будет слать этот текст когда наступит пара',
                                   verbose_name='Ссылка bbb'),
        ),
    ]
