# Generated by Django 3.0.8 on 2020-12-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0021_auto_20201027_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Обновлять расписание?'),
        ),
    ]
