# Generated by Django 5.0 on 2024-02-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='for_trusted',
            field=models.BooleanField(default=False, verbose_name='Для доверенных пользователей'),
        ),
    ]
