# Generated by Django 5.0 on 2024-01-31 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0002_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt_tokens', models.PositiveSmallIntegerField(default=0, verbose_name='Входные токены')),
                ('completion_tokens', models.PositiveSmallIntegerField(default=0, verbose_name='Выходные токены')),
                ('images_tokens', models.PositiveSmallIntegerField(default=0, verbose_name='Генерация картинок')),
                ('cost', models.FloatField(default=0, verbose_name='Стоимость запроса')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.profile',
                                             verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'GPT использование',
                'verbose_name_plural': 'GPT использования',
            },
        ),
    ]
