# Generated by Django 3.2.20 on 2023-10-08 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promocode',
        ),
    ]
