# Generated by Django 3.2.19 on 2023-06-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='service',
            field=models.SmallIntegerField(blank=True,
                                           choices=[(1, 'YouTube'), (2, 'The Hole'), (3, 'WASD'), (4, 'VK')], default=1,
                                           verbose_name='Сервис'),
        ),
    ]
