# Generated by Django 5.2.4 on 2025-11-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscopememe',
            name='type',
            field=models.CharField(blank=True, choices=[('photo', 'Фото'), ('video', 'Видео'), ('link', 'Ссылка'),
                                                        ('sticker', 'Стикер'), ('gif', 'Гифка'), ('animation', 'Гифка'),
                                                        ('voice', 'Голосовое'), ('video_note', 'Кружочек')],
                                   max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='type',
            field=models.CharField(blank=True, choices=[('photo', 'Фото'), ('video', 'Видео'), ('link', 'Ссылка'),
                                                        ('sticker', 'Стикер'), ('gif', 'Гифка'), ('animation', 'Гифка'),
                                                        ('voice', 'Голосовое'), ('video_note', 'Кружочек')],
                                   max_length=10, verbose_name='Тип'),
        ),
    ]
