# Generated by Django 3.0.8 on 2020-07-28 14:12

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='timezone',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='service.TimeZone', verbose_name='Временная зона UTC'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='text',
            field=models.TextField(verbose_name='Фича'),
        ),
        migrations.AlterField(
            model_name='latermessage',
            name='attachments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Вложения'),
        ),
        migrations.AlterField(
            model_name='notify',
            name='attachments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Вложения'),
        ),
    ]
