# Generated by Django 3.1.8 on 2021-08-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='type',
            field=models.CharField(blank=True, choices=[('photo', 'Фото'), ('video', 'Видео'), ('audio', 'Аудио'), ('doc', 'Документ'), ('link', 'Ссылка')], max_length=5, verbose_name='Тип'),
        ),
    ]
