# Generated by Django 5.0 on 2024-01-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0003_alter_bot_id_alter_chat_id_alter_profile_id'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTPrePrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', verbose_name='ChatGPT preprompt')),
                ('provider',
                 models.CharField(blank=True, choices=[('chatgpt', 'СhatGPT'), ('gigachat', 'Gigachat')], max_length=10,
                                  verbose_name='Провайдер')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.profile',
                                             verbose_name='Пользователь')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chat',
                                           verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'GPT препромпт',
                'verbose_name_plural': 'GPT препромпты',
                'unique_together': {('author', 'chat')},
            },
        ),
    ]
