# Generated by Django 5.0 on 2024-01-28 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0005_rename_gamer2_profile_gamer'),
        ('service', '0002_gptpreprompt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gptpreprompt',
            unique_together={('author', 'chat', 'provider')},
        ),
    ]
