# Generated by Django 3.1.8 on 2021-08-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210814_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latermessagesession',
            name='author',
        ),
        migrations.RemoveField(
            model_name='latermessagesession',
            name='later_messages',
        ),
        migrations.DeleteModel(
            name='LaterMessage',
        ),
        migrations.DeleteModel(
            name='LaterMessageSession',
        ),
    ]
