# Generated by Django 3.0.8 on 2020-12-19 09:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200728_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Данные')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='issue',
            name='author',
        ),
        migrations.DeleteModel(
            name='AudioList',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
