# Generated by Django 3.2.19 on 2023-05-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0002_auto_20230511_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscopememe',
            name='type',
            field=models.CharField(blank=True, choices=[('photo', 'Фото'), ('video', 'Видео'), ('link', 'Ссылка'),
                                                        ('sticker', 'Стикер'), ('gif', 'Гифка'), ('voice', 'Голосовое'),
                                                        ('video_note', 'Кружочек')], max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='type',
            field=models.CharField(blank=True, choices=[('photo', 'Фото'), ('video', 'Видео'), ('link', 'Ссылка'),
                                                        ('sticker', 'Стикер'), ('gif', 'Гифка'), ('voice', 'Голосовое'),
                                                        ('video_note', 'Кружочек')], max_length=10, verbose_name='Тип'),
        ),
    ]
