# Generated by Django 5.2.4 on 2025-12-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0002_alter_horoscopememe_type_alter_meme_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscopememe',
            name='file',
            field=models.FileField(null=True, upload_to='service/memes', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='meme',
            name='file',
            field=models.FileField(null=True, upload_to='service/memes', verbose_name='Файл'),
        ),
    ]
