# Generated by Django 3.2.20 on 2023-10-08 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0002_initial'),
        ('service', '0002_delete_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('expiration', models.DateField(blank=True, null=True, verbose_name='Окончание действия промокода')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.profile',
                                             verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['name'],
                'unique_together': {('name', 'code')},
            },
        ),
    ]
