# Generated by Django 3.2.20 on 2023-10-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0002_alter_subscribe_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='playlist_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название плейлиста'),
        ),
    ]
