# Generated by Django 5.0 on 2024-02-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0003_remove_notify_for_trusted_horoscopememe_for_trusted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wakeonlanuserdata',
            name='ip',
            field=models.TextField(verbose_name='IP'),
        ),
    ]
