# Generated by Django 3.0.8 on 2020-12-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_taxiinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='author',
        ),
        migrations.DeleteModel(
            name='AudioList',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
