# Generated by Django 3.1.12 on 2021-08-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210820_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='attachments',
            field=models.JSONField(blank=True, default=dict, verbose_name='Вложения'),
        ),
        migrations.AlterField(
            model_name='taxiinfo',
            name='data',
            field=models.JSONField(default=dict, verbose_name='Данные'),
        ),
    ]
