# Generated by Django 3.2.20 on 2023-10-28 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0003_subscribe_playlist_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ['channel_title'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RenameField(
            model_name='subscribe',
            old_name='title',
            new_name='channel_title',
        ),
    ]
