# Generated by Django 3.2.19 on 2023-05-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0003_auto_20230511_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscopememe',
            name='meme_pk',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='ID мема'),
        ),
    ]
