# Generated by Django 5.2.4 on 2025-12-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0003_horoscopememe_file_meme_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscopememe',
            name='file_preview',
            field=models.FileField(null=True, upload_to='service/memes_preview', verbose_name='Файл превью'),
        ),
        migrations.AddField(
            model_name='meme',
            name='file_preview',
            field=models.FileField(null=True, upload_to='service/memes_preview', verbose_name='Файл превью'),
        ),
    ]
