# Generated by Django 3.2.19 on 2023-06-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0003_videocache'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='save_to_plex',
            field=models.BooleanField(default=False, verbose_name='Сохранять в plex'),
        ),
    ]
