# Generated by Django 3.2.20 on 2023-10-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0003_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='is_personal',
            field=models.BooleanField(default=False, verbose_name='Персональный'),
        ),
    ]
