# Generated by Django 5.2.4 on 2026-01-02 01:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0004_horoscopememe_file_preview_meme_file_preview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
