# Generated by Django 3.1.12 on 2021-08-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210820_0158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
