# Generated by Django 3.2.19 on 2023-06-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0004_subscribe_save_to_plex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocache',
            name='file_id',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='playlist_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID плейлиста'),
        ),
    ]
