# Generated by Django 5.0 on 2024-02-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0004_alter_wakeonlanuserdata_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wakeonlanuserdata',
            name='ip',
            field=models.CharField(max_length=16, verbose_name='IP'),
        ),
    ]
