# Generated by Django 3.2.20 on 2023-10-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0004_auto_20231028_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='playlist_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название плейлиста'),
        ),
    ]
