# Generated by Django 3.2.20 on 2023-10-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0004_promocode_is_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Описание'),
        ),
    ]
