# Generated by Django 5.0.2 on 2024-03-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0005_alter_wakeonlanuserdata_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
    ]
