# Generated by Django 3.2.20 on 2023-09-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0005_auto_20230604_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='service',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'YouTube'), (2, 'The Hole'), (3, 'WASD'), (4, 'VK'),
                                                                (5, 'Premiere')], default=1, verbose_name='Сервис'),
        ),
    ]
