# Generated by Django 3.2.20 on 2023-10-29 04:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0005_alter_subscribe_playlist_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='text_for_filter',
        ),
    ]
