# Generated by Django 5.2.4 on 2026-01-02 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0005_delete_donation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
        migrations.DeleteModel(
            name='SubscribeItem',
        ),
    ]
