# Generated by Django 3.2.20 on 2023-10-29 05:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0006_remove_notify_text_for_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='repeat',
        ),
    ]
