# Generated by Django 5.0.2 on 2024-04-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0006_horoscope_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptusage',
            name='whisper_seconds',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Секунды распознования'),
        ),
    ]
