# Generated by Django 5.2.9 on 2026-01-24 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0006_delete_subscribe_delete_subscribeitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
