# Generated by Django 5.2.9 on 2026-01-24 21:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0007_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='horoscope',
            name='memes',
        ),
        migrations.RemoveField(
            model_name='horoscopememe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='author',
        ),
        migrations.RemoveField(
            model_name='notify',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='notify',
            name='user',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='VideoCache',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='TimeZone',
        ),
        migrations.DeleteModel(
            name='Horoscope',
        ),
        migrations.DeleteModel(
            name='HoroscopeMeme',
        ),
        migrations.DeleteModel(
            name='Meme',
        ),
        migrations.DeleteModel(
            name='Notify',
        ),
    ]
