# Generated by Django 3.2.20 on 2023-11-17 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0007_remove_notify_repeat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaxiInfo',
        ),
    ]
