# Generated by Django 3.1.12 on 2021-09-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20210904_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='crontab',
            field=models.CharField(max_length=100, null=True, verbose_name='Crontab'),
        ),
    ]
