# Generated by Django 5.0.2 on 2024-04-23 18:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0007_gptusage_whisper_seconds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gptusage',
            old_name='whisper_seconds',
            new_name='voice_recognition_seconds',
        ),
    ]
