# Generated by Django 3.2.20 on 2023-09-25 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0007_auto_20230925_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='date',
        ),
    ]
