# Generated by Django 3.2.20 on 2023-11-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0008_delete_taxiinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscopememe',
            name='inline_uses',
            field=models.PositiveIntegerField(default=0, verbose_name='Рекомендаций в inline'),
        ),
        migrations.AddField(
            model_name='meme',
            name='inline_uses',
            field=models.PositiveIntegerField(default=0, verbose_name='Рекомендаций в inline'),
        ),
    ]
