# Generated by Django 5.0.4 on 2024-05-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0008_rename_whisper_seconds_gptusage_voice_recognition_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gptusage',
            name='images_tokens',
        ),
        migrations.AddField(
            model_name='gptusage',
            name='images_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество картинок'),
        ),
    ]
