# Generated by Django 3.1.12 on 2021-09-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20210904_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='crontab',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Crontab'),
        ),
        migrations.AlterField(
            model_name='notify',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата напоминания'),
        ),
    ]
