# Generated by Django 5.0 on 2023-12-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0009_auto_20231123_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='last_videos_id',
            field=models.JSONField(blank=True, max_length=100, null=True, verbose_name='ID последних видео'),
        ),
    ]
