# Generated by Django 5.0.4 on 2024-05-17 20:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0009_remove_gptusage_images_tokens_gptusage_images_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gptusage',
            name='completion_tokens',
        ),
        migrations.RemoveField(
            model_name='gptusage',
            name='images_count',
        ),
        migrations.RemoveField(
            model_name='gptusage',
            name='prompt_tokens',
        ),
        migrations.RemoveField(
            model_name='gptusage',
            name='voice_recognition_seconds',
        ),
    ]
