# Generated by Django 5.0.4 on 2024-05-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0010_remove_gptusage_completion_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptpreprompt',
            name='provider',
            field=models.CharField(blank=True,
                                   choices=[('chatgpt', 'СhatGPT'), ('gigachat', 'Gigachat'), ('gemini', 'Gemini')],
                                   max_length=10, verbose_name='Провайдер'),
        ),
    ]
