# Generated by Django 5.0 on 2023-12-24 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0010_subscribe_last_videos_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='last_video_id',
        ),
    ]
