# Generated by Django 3.2.20 on 2023-10-08 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0010_promocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['name'], 'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AlterUniqueTogether(
            name='promocode',
            unique_together={('name', 'code')},
        ),
    ]
