# Generated by Django 3.2.7 on 2021-10-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_remove_notify_attachments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
