# Generated by Django 5.0.4 on 2024-05-18 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0012_alter_usersettings_gpt_model'),
        ('service', '0011_alter_gptpreprompt_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptpreprompt',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='bot.profile', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='gptpreprompt',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chat',
                                    verbose_name='Чат'),
        ),
    ]
