# Generated by Django 5.0 on 2023-12-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0011_remove_subscribe_last_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='service',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'YouTube'), (4, 'VK'), (5, 'Premiere')], default=1,
                                           verbose_name='Сервис'),
        ),
    ]
