# Generated by Django 3.2.7 on 2021-11-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_delete_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotebook',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='wakeonlanuserdata',
            old_name='user',
            new_name='author',
        ),
    ]
