# Generated by Django 5.0.4 on 2024-05-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0012_alter_gptpreprompt_author_alter_gptpreprompt_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
