# Generated by Django 3.2.7 on 2021-11-05 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20211105_1506'),
        ('service', '0012_auto_20211105_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.user', verbose_name='Пользователь'),
        ),
    ]
