# Generated by Django 3.2.7 on 2021-11-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_notify_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notify',
            options={'ordering': ['user'], 'verbose_name': 'напоминание', 'verbose_name_plural': 'напоминания'},
        ),
        migrations.RemoveField(
            model_name='notify',
            name='author',
        ),
    ]
