# Generated by Django 5.0.4 on 2024-05-25 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0013_alter_donations_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donations',
            new_name='Donation',
        ),
    ]
