# Generated by Django 3.2.9 on 2022-01-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_auto_20211105_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='mention_sender',
            field=models.BooleanField(default=True, verbose_name='Упоминать автора'),
        ),
    ]
