# Generated by Django 3.2.12 on 2022-03-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0015_notify_mention_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
    ]
