# Generated by Django 3.2.12 on 2022-03-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0016_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='type',
            field=models.CharField(blank=True, choices=[('photo', 'Фото'), ('video', 'Видео'), ('audio', 'Аудио'),
                                                        ('doc', 'Документ'), ('link', 'Ссылка'), ('sticker', 'Стикер')],
                                   max_length=10, verbose_name='Тип'),
        ),
    ]
