# Generated by Django 5.0.4 on 2024-05-26 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0016_alter_donation_created_at_alter_donation_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'город', 'verbose_name_plural': 'города'},
        ),
        migrations.AlterModelOptions(
            name='horoscopememe',
            options={'verbose_name': 'мем гороскопа', 'verbose_name_plural': 'мемы гороскопа'},
        ),
        migrations.AlterModelOptions(
            name='meme',
            options={'verbose_name': 'мем', 'verbose_name_plural': 'мемы'},
        ),
        migrations.AlterModelOptions(
            name='notify',
            options={'verbose_name': 'напоминание', 'verbose_name_plural': 'напоминания'},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='timezone',
            options={'verbose_name': 'таймзона', 'verbose_name_plural': 'таймзоны'},
        ),
        migrations.AlterModelOptions(
            name='videocache',
            options={'verbose_name': 'Кэш видео', 'verbose_name_plural': 'Кэши видео'},
        ),
        migrations.AlterModelOptions(
            name='words',
            options={'verbose_name': 'Слово', 'verbose_name_plural': 'Слова'},
        ),
    ]
