# Generated by Django 3.2.12 on 2022-03-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0017_alter_meme_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='sticker_file_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='file_id стикера в телеграме'),
        ),
    ]
