# Generated by Django 5.0.6 on 2024-07-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0017_alter_city_options_alter_horoscopememe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocache',
            name='filename',
            field=models.CharField(max_length=1024, verbose_name='Название файла'),
        ),
    ]
