# Generated by Django 5.0.7 on 2024-07-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0018_alter_videocache_filename'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promocode',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='author',
        ),
        migrations.RemoveField(
            model_name='wakeonlanuserdata',
            name='author',
        ),
        migrations.DeleteModel(
            name='Words',
        ),
        migrations.AlterField(
            model_name='gptpreprompt',
            name='provider',
            field=models.CharField(blank=True, choices=[('chatgpt', 'СhatGPT'), ('gemini', 'Gemini')], max_length=10,
                                   verbose_name='Провайдер'),
        ),
        migrations.DeleteModel(
            name='Promocode',
        ),
        migrations.DeleteModel(
            name='WakeOnLanUserData',
        ),
    ]
