# Generated by Django 3.2.12 on 2022-04-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0018_meme_sticker_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilanaTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milana_text', models.CharField(max_length=30, verbose_name='Текст Миланы')),
                ('translated_text', models.CharField(max_length=30, verbose_name='Переведённый текст')),
            ],
        ),
    ]
