# Generated by Django 3.2.12 on 2022-05-14 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0015_chat_use_swear'),
        ('service', '0019_milanatranslate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YoutubeSubscribe',
            new_name='Subscribe',
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ['title'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
