# Generated by Django 5.0.7 on 2024-08-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0019_alter_promocode_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='save_to_plex',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='save_to_disk',
            field=models.BooleanField(default=False, verbose_name='Сохранять на диск'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='service',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'YouTube'), (4, 'VK')], default=1,
                                           verbose_name='Сервис'),
        ),
    ]
