# Generated by Django 3.2.12 on 2022-05-14 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0015_chat_use_swear'),
        ('service', '0021_auto_20220514_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.user',
                                    verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней публикации'),
        ),
    ]
