# Generated by Django 5.1 on 2024-08-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0021_subscribe_high_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='force_cache',
            field=models.BooleanField(default=False, verbose_name='Принудительно кэшировать'),
        ),
    ]
