# Generated by Django 3.2.12 on 2022-05-14 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0022_auto_20220514_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'Домены', 'verbose_name_plural': 'Домен'},
        ),
        migrations.AlterModelOptions(
            name='milanatranslate',
            options={'verbose_name': 'Словечки Миланы', 'verbose_name_plural': 'Словечко Миланы'},
        ),
        migrations.AlterModelOptions(
            name='taxiinfo',
            options={'verbose_name': 'Инфо о такси', 'verbose_name_plural': 'Инфо о такси'},
        ),
    ]
