# Generated by Django 5.1 on 2024-08-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0022_subscribe_force_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptpreprompt',
            name='provider',
            field=models.CharField(blank=True,
                                   choices=[('chatgpt', 'СhatGPT'), ('gemini', 'Gemini'), ('claude', 'Claude')],
                                   max_length=10, verbose_name='Провайдер'),
        ),
    ]
