# Generated by Django 5.1 on 2024-09-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0023_alter_gptpreprompt_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocache',
            name='original_url',
            field=models.URLField(blank=True, max_length=1024, verbose_name='Ссылка на оригинальное видео'),
        ),
    ]
