# Generated by Django 3.2.12 on 2022-05-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0023_auto_20220514_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='last_video_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID последнего видео'),
        ),
    ]
