# Generated by Django 5.1 on 2024-10-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0024_videocache_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocache',
            name='video',
            field=models.FileField(blank=True, max_length=1024, upload_to='service/video/', verbose_name='Видео'),
        ),
    ]
