# Generated by Django 3.2.12 on 2022-05-14 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0024_alter_subscribe_last_video_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
