# Generated by Django 3.2.12 on 2022-05-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0025_delete_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='is_stream',
            field=models.BooleanField(blank=True, default=False, verbose_name='Флаг стрима'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='last_stream_status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Последнее состояние стрима'),
        ),
    ]
