# Generated by Django 5.1 on 2024-12-04 19:50

import django.db.models.deletion
from django.db import migrations, models


def add_subscribe_item_data(apps, schema_editor):
    SubscribeItem = apps.get_model('service', 'SubscribeItem')
    Subscribe = apps.get_model('service', 'Subscribe')

    subscribes = Subscribe.objects.all()
    for subscribe in subscribes:
        subscribe_item, _ = SubscribeItem.objects.get_or_create(
            channel_id=subscribe.channel_id,
            channel_title=subscribe.channel_title,
            playlist_id=subscribe.playlist_id,
            playlist_title=subscribe.playlist_title,
            service=subscribe.service,
            defaults={
                'last_videos_id': subscribe.last_videos_id,
            }
        )
        subscribe.subscribe_item = subscribe_item
        subscribe.save()


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0025_alter_videocache_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('channel_id', models.CharField(max_length=100, verbose_name='ID канала')),
                ('channel_title', models.CharField(max_length=100, verbose_name='Название канала')),
                ('playlist_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID плейлиста')),
                ('playlist_title',
                 models.CharField(blank=True, max_length=100, null=True, verbose_name='Название плейлиста')),
                ('last_videos_id', models.JSONField(null=True, verbose_name='ID последних видео')),
                ('service', models.SmallIntegerField(blank=True, choices=[(1, 'YouTube'), (4, 'VK')], default=1,
                                                     verbose_name='Сервис')),
            ],
            options={
                'verbose_name': 'Элемент подписки',
                'verbose_name_plural': 'Элементы подписки',
            },
        ),

        migrations.AddField(
            model_name='subscribe',
            name='subscribe_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribes',
                                    to='service.subscribeitem', verbose_name='Сервис подписки'),
        ),
        migrations.RunPython(add_subscribe_item_data, migrations.RunPython.noop),

        migrations.RemoveField(
            model_name='subscribe',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='channel_title',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='last_videos_id',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='playlist_id',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='playlist_title',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='service',
        ),
    ]
