# Generated by Django 5.1.4 on 2025-01-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0026_subscribeitem_remove_subscribe_channel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptpreprompt',
            name='provider',
            field=models.CharField(blank=True,
                                   choices=[('chatgpt', 'СhatGPT'), ('gemini', 'Gemini'), ('claude', 'Claude'),
                                            ('grok', 'Grok')], max_length=10, verbose_name='Провайдер'),
        ),
    ]
