# Generated by Django 5.1.6 on 2025-05-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0027_alter_gptpreprompt_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptusage',
            name='provider',
            field=models.CharField(blank=True,
                                   choices=[('chatgpt', 'СhatGPT'), ('gemini', 'Gemini'), ('claude', 'Claude'),
                                            ('grok', 'Grok')], max_length=10, verbose_name='Провайдер'),
        ),
    ]
