# Generated by Django 3.2.13 on 2022-05-21 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0027_alter_subscribe_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milanatranslate',
            options={'verbose_name': 'Словечко Миланы', 'verbose_name_plural': 'Словечки Миланы'},
        ),
    ]
