# Generated by Django 5.1.6 on 2025-05-03 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0028_gptusage_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gptusage',
            name='author',
        ),
        migrations.DeleteModel(
            name='GPTPrePrompt',
        ),
        migrations.DeleteModel(
            name='GPTUsage',
        ),
    ]
