# Generated by Django 3.2.13 on 2022-08-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0015_chat_use_swear'),
        ('service', '0029_auto_20220812_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('chat',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.chat', verbose_name='Чат')),
                ('users', models.ManyToManyField(blank=True, to='bot.Profile', verbose_name='Пользователи')),
            ],
        ),
    ]
