# Generated by Django 3.2.13 on 2022-08-19 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0015_chat_use_swear'),
        ('service', '0030_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'chat')},
        ),
    ]
