# Generated by Django 3.2.13 on 2022-10-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0031_auto_20220819_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='attachments',
            field=models.JSONField(blank=True, default=dict, verbose_name='Вложения'),
        ),
    ]
