# Generated by Django 3.2.13 on 2022-12-15 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0033_alter_notify_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='sticker_file_id',
            new_name='tg_file_id',
        ),
    ]
