# Generated by Django 3.2.13 on 2022-12-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0034_rename_sticker_file_id_meme_tg_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='type',
            field=models.CharField(blank=True, choices=[('photo', 'Фото'), ('video', 'Видео'), ('audio', 'Аудио'),
                                                        ('doc', 'Документ'), ('link', 'Ссылка'), ('sticker', 'Стикер'),
                                                        ('gif', 'Гифка'), ('voice', 'Голосовое')], max_length=10,
                                   verbose_name='Тип'),
        ),
    ]
