# Generated by Django 3.2.13 on 2023-03-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0036_auto_20230102_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='youtube_ignore_shorts',
            field=models.BooleanField(blank=True, default=False, verbose_name='Игнорировать Youtube shorts'),
        ),
    ]
