# Generated by Django 3.2.13 on 2023-05-10 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0037_subscribe_youtube_ignore_shorts'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoroscopeMeme',
            fields=[
                ('meme_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='service.meme')),
            ],
            bases=('service.meme',),
        ),
        migrations.AlterField(
            model_name='horoscope',
            name='memes',
            field=models.ManyToManyField(to='service.HoroscopeMeme'),
        ),
    ]
