# Generated by Django 3.2.13 on 2023-05-10 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0015_chat_use_swear'),
        ('service', '0039_auto_20230510_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoroscopeMeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Название')),
                ('link', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Ссылка')),
                ('type', models.CharField(blank=True,
                                          choices=[('photo', 'Фото'), ('video', 'Видео'), ('audio', 'Аудио'),
                                                   ('doc', 'Документ'), ('link', 'Ссылка'), ('sticker', 'Стикер'),
                                                   ('gif', 'Гифка'), ('voice', 'Голосовое')], max_length=10,
                                          verbose_name='Тип')),
                ('uses', models.PositiveIntegerField(default=0, verbose_name='Использований')),
                ('approved', models.BooleanField(default=False, verbose_name='Разрешённый')),
                (
                'tg_file_id', models.CharField(blank=True, max_length=128, verbose_name='file_id стикера в телеграме')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.profile',
                                             verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'мем гороскопа',
                'verbose_name_plural': 'мемы гороскопа',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memes', models.ManyToManyField(to='service.HoroscopeMeme')),
            ],
            options={
                'verbose_name': 'Гороскоп',
                'verbose_name_plural': 'Гороскопы',
            },
        ),
    ]
