# Generated by Django 3.2.19 on 2023-05-10 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0040_horoscope_horoscopememe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotebook',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='quotebook',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Counter',
        ),
        migrations.DeleteModel(
            name='QuoteBook',
        ),
    ]
