# Generated by Django 3.2.1 on 2021-07-12 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('imei', models.CharField(max_length=20, null=True, verbose_name='IMEI')),
                ('event', models.CharField(choices=[('home', 'дома'), ('work', 'работа'), ('university', 'университет'), ('somewhere', 'где-то')], max_length=20, null=True, verbose_name='Событие')),
                ('msg', models.CharField(max_length=2000, verbose_name='Сообщение')),
                ('success', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.users', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Журнал событий',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logger_name', models.CharField(max_length=100, verbose_name='Логгер')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'NOTSET'), (10, 'DEBUG'), (20, 'INFO'), (30, 'WARNING'), (40, 'ERROR'), (50, 'FATAL')], db_index=True, default=40, verbose_name='Уровень')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('event', models.TextField(blank=True, null=True, verbose_name='Запрос пользователя')),
                ('user_msg', models.TextField(blank=True, null=True, verbose_name='Сообщение пользователя')),
                ('msg', models.TextField(verbose_name='Сообщение')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Результат выполнения')),
                ('exception', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('traceback', models.TextField(blank=True, null=True, verbose_name='Traceback')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.chat', verbose_name='Чат')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
