# Generated by Django 3.0.8 on 2020-12-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logger',
            options={'ordering': ('-create_datetime',), 'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
    ]
