# Generated by Django 3.1.8 on 2021-08-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_logger', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovementLog',
        ),
    ]
