# Generated by Django 5.1.6 on 2025-05-03 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('bot', '0027_alter_profilesettings_chat_gpt_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('provider', models.CharField(
                    choices=[('chatgpt', 'CHATGPT'), ('gemini', 'GEMINI'), ('claude', 'CLAUDE'), ('grok', 'GROK')],
                    max_length=10, verbose_name='Провайдер')),
                ('cost', models.FloatField(default=0, verbose_name='Стоимость запроса')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.profile',
                                             verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'GPT использование',
                'verbose_name_plural': 'GPT использования',
            },
        ),
        migrations.CreateModel(
            name='Preprompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('provider', models.CharField(
                    choices=[('chatgpt', 'CHATGPT'), ('gemini', 'GEMINI'), ('claude', 'CLAUDE'), ('grok', 'GROK')],
                    max_length=10, verbose_name='Провайдер')),
                ('text', models.TextField(blank=True, default='', verbose_name='ChatGPT preprompt')),
                ('author',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.profile',
                                   verbose_name='Пользователь')),
                ('chat',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chat',
                                   verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'GPT препромпт',
                'verbose_name_plural': 'GPT препромпты',
                'unique_together': {('author', 'chat', 'provider')},
            },
        ),
    ]
