# Generated by Django 5.1.6 on 2025-05-03 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0027_alter_profilesettings_chat_gpt_model'),
        ('gpt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('chat_gpt_key', models.CharField(blank=True, max_length=256, verbose_name='Ключ ChatGPT')),
                ('chat_gpt_model', models.CharField(blank=True, max_length=64, verbose_name='Модель ChatGPT')),
                ('gemini_key', models.CharField(blank=True, max_length=256, verbose_name='Ключ Gemini')),
                ('gemini_model', models.CharField(blank=True, max_length=64, verbose_name='Модель Gemini')),
                ('claude_key', models.CharField(blank=True, max_length=256, verbose_name='Ключ Claude')),
                ('claude_model', models.CharField(blank=True, max_length=64, verbose_name='Модель Claude')),
                ('grok_key', models.CharField(blank=True, max_length=256, verbose_name='Ключ Grok')),
                ('grok_model', models.CharField(blank=True, max_length=64, verbose_name='Модель Grok')),
                ('profile',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpt_settings',
                                      to='bot.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'GPT настройка',
                'verbose_name_plural': 'GPT настройки',
            },
        ),
    ]
