# Generated by Django 5.1.6 on 2025-05-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0002_gptsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gptsettings',
            name='gemini_key',
        ),
        migrations.RemoveField(
            model_name='gptsettings',
            name='gemini_model',
        ),
        migrations.AlterField(
            model_name='preprompt',
            name='provider',
            field=models.CharField(choices=[('chatgpt', 'CHATGPT'), ('claude', 'CLAUDE'), ('grok', 'GROK')],
                                   max_length=10, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='provider',
            field=models.CharField(choices=[('chatgpt', 'CHATGPT'), ('claude', 'CLAUDE'), ('grok', 'GROK')],
                                   max_length=10, verbose_name='Провайдер'),
        ),
    ]
