# Generated by Django 5.1.6 on 2025-05-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0003_remove_gptsettings_gemini_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='model_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Стоимость запроса'),
        ),
    ]
