# Generated by Django 5.1.6 on 2025-05-09 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0028_remove_profilesettings_chat_gpt_key_and_more'),
        ('gpt', '0004_usage_model_name_alter_usage_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('chatgpt', 'CHATGPT'), ('claude', 'CLAUDE'), ('grok', 'GROK')],
                                          max_length=10, verbose_name='Провайдер')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='preprompt',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='usage',
            name='provider',
        ),
        migrations.AlterField(
            model_name='preprompt',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст препромпта'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='cost',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Стоимость запроса'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='model_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Название модели'),
        ),
        migrations.CreateModel(
            name='ImageEditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название модели в API')),
                ('verbose_name', models.CharField(max_length=256, verbose_name='Название модели для пользователя')),
                ('is_default', models.BooleanField(default=False)),
                ('width', models.PositiveSmallIntegerField(verbose_name='Ширина картинки')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Высота картинки')),
                ('image_cost', models.DecimalField(decimal_places=4, max_digits=8,
                                                   verbose_name='Стоимость редактирования одной картинки')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt.provider',
                                               verbose_name='Провайдер')),
            ],
            options={
                'verbose_name': 'Модель редактирования изображений',
                'verbose_name_plural': 'Модели редактирования изображений',
            },
        ),
        migrations.CreateModel(
            name='ImageDrawModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название модели в API')),
                ('verbose_name', models.CharField(max_length=256, verbose_name='Название модели для пользователя')),
                ('is_default', models.BooleanField(default=False)),
                ('width', models.PositiveSmallIntegerField(verbose_name='Ширина картинки')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Высота картинки')),
                ('image_cost', models.DecimalField(decimal_places=4, max_digits=8,
                                                   verbose_name='Стоимость генерации одной картинки')),
                ('quality', models.CharField(max_length=32, verbose_name='Название качества модели в API')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt.provider',
                                               verbose_name='Провайдер')),
            ],
            options={
                'verbose_name': 'Модель рисования изображений',
                'verbose_name_plural': 'Модели рисования изображений',
            },
        ),
        migrations.CreateModel(
            name='CompletionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название модели в API')),
                ('verbose_name', models.CharField(max_length=256, verbose_name='Название модели для пользователя')),
                ('is_default', models.BooleanField(default=False)),
                ('prompt_1m_token_cost', models.DecimalField(decimal_places=4, max_digits=8,
                                                             verbose_name='Стоимость за 1млн. входных токенов')),
                ('completion_1m_token_cost', models.DecimalField(decimal_places=4, max_digits=8,
                                                                 verbose_name='Стоимость за 1млн. выходных токенов')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt.provider',
                                               verbose_name='Провайдер')),
            ],
            options={
                'verbose_name': 'Модель обработки текста',
                'verbose_name_plural': 'Модели обработки текста',
            },
        ),
        migrations.CreateModel(
            name='VisionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название модели в API')),
                ('verbose_name', models.CharField(max_length=256, verbose_name='Название модели для пользователя')),
                ('is_default', models.BooleanField(default=False)),
                ('prompt_1m_token_cost', models.DecimalField(decimal_places=4, max_digits=8,
                                                             verbose_name='Стоимость за 1млн. входных токенов')),
                ('completion_1m_token_cost', models.DecimalField(decimal_places=4, max_digits=8,
                                                                 verbose_name='Стоимость за 1млн. выходных токенов')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt.provider',
                                               verbose_name='Провайдер')),
            ],
            options={
                'verbose_name': 'Модель обработки изображений',
                'verbose_name_plural': 'Модели обработки изображений',
            },
        ),
        migrations.CreateModel(
            name='VoiceRecognitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название модели в API')),
                ('verbose_name', models.CharField(max_length=256, verbose_name='Название модели для пользователя')),
                ('is_default', models.BooleanField(default=False)),
                ('voice_recognition_1_min_cost', models.DecimalField(decimal_places=4, max_digits=8,
                                                                     verbose_name='Стоимость за 1 минуту распознования голоса')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt.provider',
                                               verbose_name='Провайдер')),
            ],
            options={
                'verbose_name': 'Модель распознования голоса',
                'verbose_name_plural': 'Модели распознования голоса',
            },
        ),
        migrations.CreateModel(
            name='ProfileGPTSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('key', models.CharField(blank=True, max_length=256, verbose_name='Ключ провайдера')),
                ('completions_model',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpt.completionmodel',
                                   verbose_name='Модель обработки текста')),
                ('image_draw_model',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpt.imagedrawmodel',
                                   verbose_name='Модель рисования изображений')),
                ('image_edit_model',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpt.imageeditmodel',
                                   verbose_name='Модель редактирования изображений')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpt_settings',
                                              to='bot.profile', verbose_name='Профиль')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt.provider',
                                               verbose_name='Провайдер')),
                ('vision_model',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpt.visionmodel',
                                   verbose_name='Модель обработки изображений')),
                ('voice_recognition_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                              to='gpt.voicerecognitionmodel',
                                                              verbose_name='Модель распознования голоса')),
            ],
            options={
                'verbose_name': 'GPT настройка пользователя',
                'verbose_name_plural': 'GPT настройки пользователя',
            },
        ),
        migrations.DeleteModel(
            name='GPTSettings',
        ),
        migrations.RemoveField(
            model_name='preprompt',
            name='provider',
        ),
    ]
