# Generated by Django 5.1.6 on 2025-05-09 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0028_remove_profilesettings_chat_gpt_key_and_more'),
        ('gpt', '0005_provider_alter_preprompt_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preprompt',
            options={'verbose_name': 'Препромпт', 'verbose_name_plural': 'Препромпты'},
        ),
        migrations.AlterModelOptions(
            name='profilegptsettings',
            options={'verbose_name': 'Настройка пользователя', 'verbose_name_plural': 'Настройки пользователя'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Провайдер', 'verbose_name_plural': 'Провайдеры'},
        ),
        migrations.AlterModelOptions(
            name='usage',
            options={'verbose_name': 'Использование', 'verbose_name_plural': 'Использования'},
        ),
        migrations.AddField(
            model_name='preprompt',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gpt.provider',
                                    verbose_name='Провайдер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usage',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gpt.provider',
                                    verbose_name='Провайдер'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='preprompt',
            unique_together={('author', 'chat', 'provider')},
        ),
    ]
