# Generated by Django 5.2.4 on 2025-09-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0005_gptpreset_delete_profilegptpreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptpreset',
            name='description',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='gptpreset',
            name='preprompt_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст препромпта'),
        ),
    ]
