# Generated by Django 5.1.6 on 2025-05-09 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0006_alter_preprompt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilegptsettings',
            name='completions_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='gpt.completionmodel', verbose_name='Модель обработки текста'),
        ),
        migrations.AlterField(
            model_name='profilegptsettings',
            name='image_draw_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='gpt.imagedrawmodel', verbose_name='Модель рисования изображений'),
        ),
        migrations.AlterField(
            model_name='profilegptsettings',
            name='image_edit_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='gpt.imageeditmodel', verbose_name='Модель редактирования изображений'),
        ),
        migrations.AlterField(
            model_name='profilegptsettings',
            name='vision_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='gpt.visionmodel', verbose_name='Модель обработки изображений'),
        ),
        migrations.AlterField(
            model_name='profilegptsettings',
            name='voice_recognition_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='gpt.voicerecognitionmodel', verbose_name='Модель распознования голоса'),
        ),
    ]
