# Generated by Django 5.2.4 on 2025-09-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0007_alter_gptpreset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptpreset',
            name='use_debug',
            field=models.BooleanField(null=True, verbose_name='Дебаг режим'),
        ),
        migrations.AddField(
            model_name='profilegptsettings',
            name='use_debug',
            field=models.BooleanField(null=True, verbose_name='Дебаг режим'),
        ),
    ]
