# Generated by Django 5.1.6 on 2025-05-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0007_alter_profilegptsettings_completions_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completionmodel',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название модели в API'),
        ),
        migrations.AlterField(
            model_name='imagedrawmodel',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название модели в API'),
        ),
        migrations.AlterField(
            model_name='imageeditmodel',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название модели в API'),
        ),
        migrations.AlterField(
            model_name='visionmodel',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название модели в API'),
        ),
        migrations.AlterField(
            model_name='voicerecognitionmodel',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название модели в API'),
        ),
        migrations.AddConstraint(
            model_name='completionmodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name_completion_model'),
        ),
        migrations.AddConstraint(
            model_name='imagedrawmodel',
            constraint=models.UniqueConstraint(fields=('name', 'width', 'height', 'quality'),
                                               name='unique_name_width_height_quality_img_draw'),
        ),
        migrations.AddConstraint(
            model_name='imageeditmodel',
            constraint=models.UniqueConstraint(fields=('name', 'width', 'height'),
                                               name='unique_name_width_height_image_edit'),
        ),
        migrations.AddConstraint(
            model_name='visionmodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name_vision_model'),
        ),
        migrations.AddConstraint(
            model_name='voicerecognitionmodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name_voice_recognition_model'),
        ),
    ]
