# Generated by Django 5.1.6 on 2025-05-10 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0009_models_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletionModel',
            new_name='CompletionsModel',
        ),
    ]
