# Generated by Django 5.2.4 on 2025-11-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0010_completionsmodel_web_search_1k_token_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptpreset',
            name='gpt_5_settings_reasoning_effort_level',
            field=models.CharField(blank=True, choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW'),
                                                        ('minimal', 'MINIMAL'), (None, 'NONE')], max_length=32,
                                   null=True, verbose_name='Уровень рассуждений моделей семейства gpt-5'),
        ),
        migrations.AlterField(
            model_name='profilegptsettings',
            name='gpt_5_settings_reasoning_effort_level',
            field=models.CharField(blank=True, choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW'),
                                                        ('minimal', 'MINIMAL'), (None, 'NONE')], max_length=32,
                                   null=True, verbose_name='Уровень рассуждений моделей семейства gpt-5'),
        ),
    ]
