# Generated by Django 5.1.6 on 2025-05-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0010_rename_completionmodel_completionsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagedrawmodel',
            options={'verbose_name': 'Модель генерации изображений',
                     'verbose_name_plural': 'Модели генерации изображений'},
        ),
        migrations.AlterField(
            model_name='imagedrawmodel',
            name='height',
            field=models.PositiveSmallIntegerField(verbose_name='Высота изображения'),
        ),
        migrations.AlterField(
            model_name='imagedrawmodel',
            name='image_cost',
            field=models.DecimalField(decimal_places=4, max_digits=8,
                                      verbose_name='Стоимость генерации одного изображения'),
        ),
        migrations.AlterField(
            model_name='imagedrawmodel',
            name='width',
            field=models.PositiveSmallIntegerField(verbose_name='Ширина изображения'),
        ),
        migrations.AlterField(
            model_name='imageeditmodel',
            name='height',
            field=models.PositiveSmallIntegerField(verbose_name='Высота изображения'),
        ),
        migrations.AlterField(
            model_name='imageeditmodel',
            name='image_cost',
            field=models.DecimalField(decimal_places=4, max_digits=8,
                                      verbose_name='Стоимость редактирования одного изображения'),
        ),
        migrations.AlterField(
            model_name='imageeditmodel',
            name='width',
            field=models.PositiveSmallIntegerField(verbose_name='Ширина изображения'),
        ),
    ]
