# Generated by Django 5.2.9 on 2026-01-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0011_alter_gptpreset_gpt_5_settings_reasoning_effort_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(choices=[('chatgpt', 'CHATGPT'), ('grok', 'GROK')], max_length=32, unique=True,
                                   verbose_name='Провайдер'),
        ),
    ]
