# Generated by Django 5.1.6 on 2025-05-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0011_alter_imagedrawmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='cost',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Стоимость запроса'),
        ),
    ]
