# Generated by Django 5.1.6 on 2025-05-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0012_alter_usage_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(choices=[('chatgpt', 'CHATGPT'), ('claude', 'CLAUDE'), ('grok', 'GROK')],
                                   max_length=32, unique=True, verbose_name='Провайдер'),
        ),
    ]
