# Generated by Django 5.1.6 on 2025-05-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gpt', '0013_alter_provider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilegptsettings',
            name='key',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Ключ провайдера'),
        ),
    ]
