# Generated by Django 5.2.9 on 2026-01-24 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0006_alter_profile_city'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petrovichgame',
            options={'verbose_name': 'Петрович игра', 'verbose_name_plural': 'Петрович игры'},
        ),
        migrations.AlterField(
            model_name='petrovichgame',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.profile',
                                    verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='petrovichuser',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Флаг активности'),
        ),
        migrations.AlterField(
            model_name='petrovichuser',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.profile',
                                    verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='wordle',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.profile',
                                    verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='wordle',
            name='word',
            field=models.CharField(max_length=5, verbose_name='Загаданное слово'),
        ),
    ]
