# Generated by Django 5.2.9 on 2026-01-24 23:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0010_alter_profile_city'),
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='timezone',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='TimeZone',
        ),
    ]
