# Generated by Django 5.2.9 on 2026-01-24 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('bot', '0005_alter_bot_platform_alter_chat_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoroscopeMeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Название')),
                ('link', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Ссылка')),
                ('type', models.CharField(blank=True,
                                          choices=[('photo', 'Фото'), ('video', 'Видео'), ('link', 'Ссылка'),
                                                   ('sticker', 'Стикер'), ('gif', 'Гифка'), ('animation', 'Гифка'),
                                                   ('voice', 'Голосовое'), ('video_note', 'Кружочек')], max_length=10,
                                          verbose_name='Тип')),
                ('uses', models.PositiveIntegerField(default=0, verbose_name='Использований')),
                ('inline_uses', models.PositiveIntegerField(default=0, verbose_name='Рекомендаций в inline')),
                ('approved', models.BooleanField(default=False, verbose_name='Разрешённый')),
                ('for_trusted', models.BooleanField(default=False, verbose_name='Для доверенных пользователей')),
                ('file', models.FileField(null=True, upload_to='service/memes', verbose_name='Файл')),
                ('file_preview',
                 models.FileField(null=True, upload_to='service/memes_preview', verbose_name='Файл превью')),
                ('tg_file_id', models.CharField(blank=True, max_length=128, verbose_name='file_id в tg')),
                ('meme_pk', models.PositiveIntegerField(blank=True, default=0, verbose_name='ID мема')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                             to='bot.profile', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'мем гороскопа',
                'verbose_name_plural': 'мемы гороскопа',
            },
        ),
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('memes', models.ManyToManyField(to='meme.horoscopememe')),
            ],
            options={
                'verbose_name': 'Гороскоп',
                'verbose_name_plural': 'Гороскопы',
            },
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Название')),
                ('link', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Ссылка')),
                ('type', models.CharField(blank=True,
                                          choices=[('photo', 'Фото'), ('video', 'Видео'), ('link', 'Ссылка'),
                                                   ('sticker', 'Стикер'), ('gif', 'Гифка'), ('animation', 'Гифка'),
                                                   ('voice', 'Голосовое'), ('video_note', 'Кружочек')], max_length=10,
                                          verbose_name='Тип')),
                ('uses', models.PositiveIntegerField(default=0, verbose_name='Использований')),
                ('inline_uses', models.PositiveIntegerField(default=0, verbose_name='Рекомендаций в inline')),
                ('approved', models.BooleanField(default=False, verbose_name='Разрешённый')),
                ('for_trusted', models.BooleanField(default=False, verbose_name='Для доверенных пользователей')),
                ('file', models.FileField(null=True, upload_to='service/memes', verbose_name='Файл')),
                ('file_preview',
                 models.FileField(null=True, upload_to='service/memes_preview', verbose_name='Файл превью')),
                ('tg_file_id', models.CharField(blank=True, max_length=128, verbose_name='file_id в tg')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                             to='bot.profile', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'мем',
                'verbose_name_plural': 'мемы',
            },
        ),
    ]
