# Generated by Django 5.2.9 on 2026-01-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('meme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscopememe',
            name='file',
            field=models.FileField(null=True, upload_to='commands/memes/memes', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='horoscopememe',
            name='file_preview',
            field=models.FileField(null=True, upload_to='commands/memes/memes_preview', verbose_name='Файл превью'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='file',
            field=models.FileField(null=True, upload_to='commands/memes/memes', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='file_preview',
            field=models.FileField(null=True, upload_to='commands/memes/memes_preview', verbose_name='Файл превью'),
        ),
    ]
