# Generated by Django 5.2.9 on 2026-01-24 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0006_alter_profile_city'),
        ('meme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscopememe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.profile',
                                    verbose_name='Профиль автора'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.profile',
                                    verbose_name='Профиль автора'),
        ),
    ]
