# Generated by Django 6.0.3 on 2026-06-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0002_alter_horoscopememe_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscopememe',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='commands/memes/memes', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='horoscopememe',
            name='file_preview',
            field=models.FileField(blank=True, null=True, upload_to='commands/memes/memes_preview', verbose_name='Файл превью'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='commands/memes/memes', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='file_preview',
            field=models.FileField(blank=True, null=True, upload_to='commands/memes/memes_preview', verbose_name='Файл превью'),
        ),
    ]
