# Generated by Django 3.0.8 on 2020-07-15 19:26

from django.db import migrations, models

import apps.bot.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APITempUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.bot.models.random_digits, max_length=6,
                                          verbose_name='Код подтверждения')),
                ('tries', models.IntegerField(default=5, verbose_name='Кол-во попыток')),
            ],
            options={
                'verbose_name': 'API Временный пользователь',
                'verbose_name_plural': 'API Временные пользователи',
            },
        ),
        migrations.CreateModel(
            name='APIUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'API Пользователь',
                'verbose_name_plural': 'API Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('platform', models.CharField(choices=[('tg', 'Telegram'), ('vk', 'Vk')], max_length=3,
                                              verbose_name='Тип платформы')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bot_id', models.CharField(max_length=20, verbose_name='ID бота')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('platform', models.CharField(choices=[('tg', 'Telegram'), ('vk', 'Vk')], max_length=3,
                                              verbose_name='Тип платформы')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.CharField(default='', max_length=20, verbose_name='ID чата')),
                ('name', models.CharField(blank=True, default='', max_length=40, verbose_name='Название')),
                ('need_reaction', models.BooleanField(default=True, verbose_name='Реагировать')),
            ],
            options={
                'ordering': ['chat_id'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('platform', models.CharField(choices=[('tg', 'Telegram'), ('vk', 'Vk')], max_length=3,
                                              verbose_name='Тип платформы')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20, verbose_name='ID пользователя')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия')),
                ('nickname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Никнейм')),
                ('nickname_real', models.CharField(blank=True, default='', max_length=40, verbose_name='Прозвище')),
                ('gender', models.CharField(blank=True, choices=[('1', 'женский'), ('2', 'мужской'), ('', 'не указан')],
                                            default='', max_length=2, verbose_name='Пол')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('chats', models.ManyToManyField(blank=True, to='bot.Chat', verbose_name='Чаты')),
            ],
            options={
                'ordering': ['name', 'surname'],
            },
        ),
    ]
