# Generated by Django 3.2.1 on 2021-07-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('platform', models.CharField(choices=[('VK', 'vk'), ('TG', 'tg'), ('API', 'api'), ('YANDEX', 'yandex')], max_length=20, verbose_name='Тип платформы')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bot_id', models.CharField(max_length=20, verbose_name='ID бота')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('avatar', models.ImageField(blank=True, upload_to='bot/bot/avatar/', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('platform', models.CharField(choices=[('VK', 'vk'), ('TG', 'tg'), ('API', 'api'), ('YANDEX', 'yandex')], max_length=20, verbose_name='Тип платформы')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.CharField(default='', max_length=20, verbose_name='ID чата')),
                ('name', models.CharField(blank=True, default='', max_length=40, verbose_name='Название')),
                ('need_reaction', models.BooleanField(default=True, verbose_name='Реагировать на неверные команды в конфе')),
                ('mentioning', models.BooleanField(default=False, verbose_name='Работа без упоминания в конфе')),
                ('need_meme', models.BooleanField(default=False, verbose_name='Слать мемы по точному названию')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('platform', models.CharField(choices=[('VK', 'vk'), ('TG', 'tg'), ('API', 'api'), ('YANDEX', 'yandex')], max_length=20, verbose_name='Тип платформы')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=127, verbose_name='ID пользователя')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия')),
                ('nickname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Никнейм')),
                ('nickname_real', models.CharField(blank=True, max_length=40, verbose_name='Прозвище')),
                ('gender', models.CharField(blank=True, choices=[('1', 'женский'), ('2', 'мужской'), ('', 'не указан')], max_length=2, verbose_name='Пол')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('imei', models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI')),
                ('celebrate_bday', models.BooleanField(default=True, verbose_name='Поздравлять с Днём рождения')),
                ('avatar', models.ImageField(blank=True, upload_to='bot/users/avatar/', verbose_name='Аватар')),
                ('chats', models.ManyToManyField(blank=True, related_name='users', to='bot.Chat', verbose_name='Чаты')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['name', 'surname'],
            },
        ),
    ]
