# Generated by Django 5.1.6 on 2025-05-10 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bot', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='service.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(to='auth.group', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='settings', to='bot.profile', verbose_name='Профиль'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='user', to='bot.profile', verbose_name='Профиль'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('user_id', 'platform')},
        ),
    ]
