# Generated by Django 3.2.20 on 2023-10-08 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='service.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(to='auth.Group', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='chat',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='bot.profile', verbose_name='Админ'),
        ),
        migrations.AlterUniqueTogether(
            name='bot',
            unique_together={('bot_id', 'platform')},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('user_id', 'platform')},
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('chat_id', 'platform')},
        ),
    ]
