# Generated by Django 3.0.8 on 2020-07-15 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('bot', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='service.City', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(to='auth.Group', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='chat',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.Users',
                                    verbose_name='Админ'),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Chat',
                                    verbose_name='Вк чат'),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Users',
                                    verbose_name='Юзер'),
        ),
        migrations.AddField(
            model_name='apitempuser',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Chat',
                                    verbose_name='Чат'),
        ),
        migrations.AddField(
            model_name='apitempuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Users',
                                    verbose_name='Пользователь'),
        ),
    ]
