# Generated by Django 5.0.2 on 2024-02-11 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsettings',
            old_name='mentioning',
            new_name='no_mention',
        ),
    ]
