# Generated by Django 3.2.1 on 2021-07-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Забанен'),
        ),
    ]
