# Generated by Django 3.2.19 on 2023-05-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='platform',
            field=models.CharField(choices=[('TG', 'tg'), ('API', 'api')], max_length=20, verbose_name='Тип платформы'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='platform',
            field=models.CharField(choices=[('TG', 'tg'), ('API', 'api')], max_length=20, verbose_name='Тип платформы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='platform',
            field=models.CharField(choices=[('TG', 'tg'), ('API', 'api')], max_length=20, verbose_name='Тип платформы'),
        ),
    ]
