# Generated by Django 3.0.8 on 2020-07-23 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0002_auto_20200715_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'ordering': ['id'], 'verbose_name': 'Бот', 'verbose_name_plural': 'Боты'},
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['chat_id'], 'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['name', 'surname'], 'verbose_name': 'Пользователь',
                     'verbose_name_plural': 'Пользователи'},
        ),
        migrations.CreateModel(
            name='ImeiNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI')),
                ('send_notify_to',
                 models.ManyToManyField(blank=True, to='bot.Users', verbose_name='Отправлять уведомления')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='imei_notifications',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       to='bot.ImeiNotifications', verbose_name='Отправка уведомлений'),
        ),
    ]
