# Generated by Django 5.2.4 on 2025-09-28 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesettings',
            name='need_meme',
        ),
    ]
