# Generated by Django 3.2.20 on 2023-09-29 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('chat_id', 'platform')},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('user_id', 'platform')},
        ),
    ]
