# Generated by Django 5.0 on 2024-02-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsettings',
            name='gpt_preprompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='gpt_preprompt',
            field=models.TextField(blank=True),
        ),
    ]
