# Generated by Django 3.2.20 on 2023-09-29 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0003_auto_20230929_1051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bot',
            unique_together={('bot_id', 'platform')},
        ),
    ]
