# Generated by Django 5.0.2 on 2024-02-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0003_rename_mentioning_chatsettings_no_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='use_mention',
            field=models.BooleanField(default=True, verbose_name='Использовать упоминания'),
        ),
    ]
