# Generated by Django 5.0 on 2024-02-03 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0003_chatsettings_gpt_preprompt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsettings',
            name='gpt_preprompt',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='gpt_preprompt',
        ),
    ]
