# Generated by Django 3.0.8 on 2020-07-23 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0003_auto_20200723_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='imei_notifications',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.ImeiNotifications',
                                    verbose_name='Отправка уведомлений'),
        ),
    ]
