# Generated by Django 5.2.9 on 2026-01-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0003_remove_profilesettings_need_meme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsettings',
            name='need_turett',
        ),
        migrations.RemoveField(
            model_name='chatsettings',
            name='time_conversion',
        ),
        migrations.RemoveField(
            model_name='profilesettings',
            name='use_swear',
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='show_birthday_year',
            field=models.BooleanField(default=True, verbose_name='Показывать год рождения'),
        ),
    ]
