# Generated by Django 3.2.19 on 2023-05-12 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0003_auto_20230511_0348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['name'], 'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
    ]
