# Generated by Django 3.1.8 on 2021-08-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_chat_is_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='users',
            name='send_notify_to',
        ),
    ]
