# Generated by Django 5.0 on 2024-01-28 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0003_alter_bot_id_alter_chat_id_alter_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gamer',
            new_name='gamer2',
        ),
        migrations.RemoveField(
            model_name='chatsettings',
            name='gpt_preprompt',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='gpt_preprompt',
        ),
    ]
