# Generated by Django 5.2.9 on 2026-01-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0004_remove_chatsettings_need_turett_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='platform',
            field=models.CharField(choices=[('TG', 'tg')], max_length=20, verbose_name='Тип платформы'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='platform',
            field=models.CharField(choices=[('TG', 'tg')], max_length=20, verbose_name='Тип платформы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='platform',
            field=models.CharField(choices=[('TG', 'tg')], max_length=20, verbose_name='Тип платформы'),
        ),
    ]
