# Generated by Django 3.2.7 on 2021-09-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20210820_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='recognize_voice',
            field=models.BooleanField(default=True, verbose_name='Распозновать голосовые автоматически'),
        ),
    ]
