# Generated by Django 3.2.20 on 2023-10-28 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0004_alter_chat_kicked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='admin',
        ),
    ]
