# Generated by Django 3.0.8 on 2020-07-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0004_auto_20200723_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='imei_notifications',
        ),
        migrations.AddField(
            model_name='users',
            name='imei',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI'),
        ),
        migrations.AddField(
            model_name='users',
            name='send_notify_to',
            field=models.ManyToManyField(blank=True, related_name='_users_send_notify_to_+', to='bot.Users',
                                         verbose_name='Отправлять уведомления'),
        ),
        migrations.DeleteModel(
            name='ImeiNotifications',
        ),
    ]
