# Generated by Django 5.0 on 2024-01-28 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0004_rename_gamer_profile_gamer2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gamer2',
            new_name='gamer',
        ),
    ]
