# Generated by Django 3.2.20 on 2023-10-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0005_remove_chat_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Название'),
        ),
    ]
