# Generated by Django 3.2.19 on 2023-05-15 04:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0005_profile_default_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='default_platform',
        ),
    ]
