# Generated by Django 3.0.8 on 2020-07-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0005_auto_20200723_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'женский'), ('2', 'мужской'), ('', 'не указан')],
                                   max_length=2, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='users',
            name='nickname_real',
            field=models.CharField(blank=True, max_length=40, verbose_name='Прозвище'),
        ),
    ]
