# Generated by Django 3.2.7 on 2021-10-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_chat_recognize_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='need_turret',
            field=models.BooleanField(default=False, verbose_name='Слать турретные сообщения'),
        ),
    ]
