# Generated by Django 5.2.9 on 2026-01-24 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0005_alter_bot_platform_alter_chat_platform_and_more'),
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='commands.city', verbose_name='Город'),
        ),
    ]
