# Generated by Django 5.2.9 on 2026-01-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bot', '0006_alter_profile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    choices=[('администратор', 'ADMIN'), ('модератор', 'MODERATOR'), ('майнкрафт', 'MINECRAFT'),
                             ('пользователь', 'USER'), ('забанен', 'BANNED'), ('доверенный', 'TRUSTED')], max_length=32,
                    unique=True, verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='groups',
        ),
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(to='auth.group', verbose_name='Роли'),
        ),
    ]
