# Generated by Django 3.2.20 on 2023-11-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0006_alter_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chatgpt_prepromt',
            field=models.CharField(default='', max_length=500, verbose_name='ChatGPT prepromt'),
        ),
        migrations.AddField(
            model_name='profile',
            name='chatgpt_prepromt',
            field=models.CharField(default='', max_length=500, verbose_name='ChatGPT prepromt'),
        ),
    ]
