# Generated by Django 5.0.2 on 2024-04-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0006_usersettings_gpt_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='gpt_model',
            field=models.CharField(choices=[('4', 'GPT-4'), ('3.5', 'GPT-3.5')], default='4', max_length=5,
                                   verbose_name='модель GPT'),
        ),
    ]
