# Generated by Django 3.0.8 on 2020-10-22 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0006_auto_20200728_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
    ]
