# Generated by Django 3.2.7 on 2021-11-05 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_delete_cat'),
        ('games', '0005_bullsandcowssession'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bot', '0006_chat_need_turret'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Profile',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('VK', 'vk'), ('TG', 'tg'), ('API', 'api'), ('YANDEX', 'yandex')], max_length=20, verbose_name='Тип платформы')),
                ('user_id', models.CharField(max_length=127, verbose_name='ID пользователя')),
                ('nickname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Никнейм')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='bot.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['platform', 'user_id'],
            },
        ),
    ]
