# Generated by Django 3.2.7 on 2021-11-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20211105_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name', 'surname'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
