# Generated by Django 5.2.9 on 2026-01-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0007_role_remove_profile_groups_profile_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(to='bot.role', verbose_name='Роли'),
        ),
    ]
