# Generated by Django 3.2.20 on 2023-11-23 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0007_auto_20231123_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chatgpt_prepromt',
            new_name='gpt_prepromt',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='chatgpt_prepromt',
            new_name='gpt_prepromt',
        ),
    ]
