# Generated by Django 3.2.7 on 2021-11-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
    ]
