# Generated by Django 3.2.20 on 2023-11-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0008_auto_20231123_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='gpt_prepromt',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gpt_prepromt',
        ),
        migrations.AddField(
            model_name='chat',
            name='gpt_preprompt',
            field=models.CharField(default='', max_length=500, verbose_name='ChatGPT preprompt'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gpt_preprompt',
            field=models.CharField(default='', max_length=500, verbose_name='ChatGPT preprompt'),
        ),
    ]
