# Generated by Django 5.2.9 on 2026-01-24 22:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0008_alter_profile_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
    ]
