# Generated by Django 3.2.20 on 2023-12-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0009_auto_20231124_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='gpt_preprompt',
            field=models.TextField(default='', verbose_name='ChatGPT preprompt'),
        ),
    ]
