# Generated by Django 3.2.7 on 2021-11-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20211105_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['profile'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
