# Generated by Django 3.0.8 on 2020-12-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20201104_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='platform',
            field=models.CharField(choices=[('VK', 'vk'), ('TG', 'tg'), ('API', 'api')], max_length=20, verbose_name='Тип платформы'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='platform',
            field=models.CharField(choices=[('VK', 'vk'), ('TG', 'tg'), ('API', 'api')], max_length=20, verbose_name='Тип платформы'),
        ),
        migrations.AlterField(
            model_name='users',
            name='platform',
            field=models.CharField(choices=[('VK', 'vk'), ('TG', 'tg'), ('API', 'api')], max_length=20, verbose_name='Тип платформы'),
        ),
    ]
