# Generated by Django 5.0.4 on 2024-05-10 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0010_alter_usersettings_gpt_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='is_newsletter_subscriber',
        ),
    ]
