# Generated by Django 3.2.9 on 2021-11-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_platform',
            field=models.CharField(blank=True, choices=[('VK', 'vk'), ('TG', 'tg'), ('API', 'api'), ('YANDEX', 'yandex')], max_length=20, verbose_name='Тип платформы по умолчанию'),
        ),
    ]
