# Generated by Django 3.0.8 on 2021-01-13 13:16
from django.contrib.postgres.operations import UnaccentExtension

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_chat_need_meme'),
    ]

    operations = [
        UnaccentExtension()
    ]
