# Generated by Django 5.0 on 2024-01-19 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0011_alter_profile_gpt_preprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebrate_bday', models.BooleanField(default=True, verbose_name='Поздравлять с Днём рождения')),
                ('gpt_preprompt', models.TextField(default='', verbose_name='ChatGPT preprompt')),
                ('mentioning', models.BooleanField(default=False, verbose_name='Работа без упоминания в конфе')),
                ('need_turett', models.BooleanField(default=False, verbose_name='Слать туреттные сообщения')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebrate_bday', models.BooleanField(default=True, verbose_name='Поздравлять с Днём рождения')),
                ('gpt_preprompt', models.TextField(default='', verbose_name='ChatGPT preprompt')),
                ('show_birthday_year', models.BooleanField(default=True, verbose_name='Показывать год')),
                ('need_meme', models.BooleanField(default=False, verbose_name='Слать мемы по точному названию')),
                ('need_reaction', models.BooleanField(default=True, verbose_name='Реагировать на неверные команды')),
                ('use_swear', models.BooleanField(default=True, verbose_name='Использовать ругательства')),
                ('recognize_voice',
                 models.BooleanField(default=True, verbose_name='Распозновать голосовые автоматически')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chatsettings',
                                       verbose_name='Настройки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.usersettings',
                                       verbose_name='Настройки'),
        ),
    ]
