# Generated by Django 3.2.9 on 2021-11-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_profile_default_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_birthday_year',
            field=models.BooleanField(default=True, verbose_name='Показывать год'),
        ),
    ]
