# Generated by Django 5.0 on 2024-01-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0012_chatsettings_usersettings_chat_settings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='gpt_preprompt',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='mentioning',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='need_meme',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='need_reaction',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='need_turett',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='recognize_voice',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='use_swear',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='celebrate_bday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gpt_preprompt',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_birthday_year',
        ),
        migrations.AlterField(
            model_name='chatsettings',
            name='celebrate_bday',
            field=models.BooleanField(default=False, verbose_name='Поздравлять с Днём рождения'),
        ),
    ]
