# Generated by Django 3.2.9 on 2022-01-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_profile_show_birthday_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='need_turret',
        ),
        migrations.AddField(
            model_name='chat',
            name='need_turett',
            field=models.BooleanField(default=False, verbose_name='Слать туреттные сообщения'),
        ),
    ]
