# Generated by Django 5.0.4 on 2024-05-26 07:41

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0012_alter_usersettings_gpt_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 550989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='bot',
            name='updated_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 551110, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 550989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 551110, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='chatsettings',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 550989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='chatsettings',
            name='updated_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 551110, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 550989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 551110, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 550989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 551110, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 550989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='updated_at',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 26, 3, 41, 30, 551110, tzinfo=datetime.timezone.utc)),
        ),
    ]
