# Generated by Django 3.0.8 on 2021-02-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20210113_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='platform',
            field=models.CharField(choices=[('VK', 'vk'), ('TG', 'tg'), ('API', 'api'), ('YANDEX', 'yandex')], max_length=20, verbose_name='Тип платформы'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='platform',
            field=models.CharField(choices=[('VK', 'vk'), ('TG', 'tg'), ('API', 'api'), ('YANDEX', 'yandex')], max_length=20, verbose_name='Тип платформы'),
        ),
        migrations.AlterField(
            model_name='users',
            name='platform',
            field=models.CharField(choices=[('VK', 'vk'), ('TG', 'tg'), ('API', 'api'), ('YANDEX', 'yandex')], max_length=20, verbose_name='Тип платформы'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(max_length=127, verbose_name='ID пользователя'),
        ),
    ]
