# Generated by Django 3.2.12 on 2022-03-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0013_auto_20220129_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='Токен для API'),
        ),
    ]
