# Generated by Django 3.0.8 on 2021-02-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20210213_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='user',
        ),
        migrations.AddField(
            model_name='bot',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Аватар'),
        ),
        migrations.DeleteModel(
            name='APITempUser',
        ),
        migrations.DeleteModel(
            name='APIUser',
        ),
    ]
