# Generated by Django 5.0.4 on 2024-05-26 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0014_alter_bot_created_at_alter_bot_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'verbose_name': 'Бот', 'verbose_name_plural': 'Боты'},
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
