# Generated by Django 3.2.12 on 2022-05-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0014_profile_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='use_swear',
            field=models.BooleanField(default=True, verbose_name='Использовать ругательства'),
        ),
    ]
