# Generated by Django 3.0.8 on 2021-02-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_auto_20210214_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='bot/bot/avatar/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='bot/users/avatar/', verbose_name='Аватар'),
        ),
    ]
