# Generated by Django 5.0 on 2024-01-19 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0014_remove_usersettings_recognize_voice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsettings',
            options={'verbose_name': 'Настройка чата', 'verbose_name_plural': 'Настройки чатов'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Настройка профиля', 'verbose_name_plural': 'Настройки профилей'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat',
                                       to='bot.chatsettings', verbose_name='Настройки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile',
                                       to='bot.usersettings', verbose_name='Настройки'),
        ),
    ]
