# Generated by Django 5.0 on 2024-01-28 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0015_alter_chatsettings_options_and_more'),
        ('games', '0003_alter_gamer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gamer2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile2',
                                       to='games.gamer', verbose_name='Игрок'),
        ),
    ]
