# Generated by Django 3.0.8 on 2021-03-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20210214_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='mentioning',
            field=models.BooleanField(default=True, verbose_name='Работа без упоминания в конфе'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='need_meme',
            field=models.BooleanField(default=False, verbose_name='Слать мемы по точному названию'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='need_reaction',
            field=models.BooleanField(default=True, verbose_name='Реагировать на неверные команды в конфе'),
        ),
    ]
