# Generated by Django 3.0.8 on 2021-03-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20210314_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='mentioning',
            field=models.BooleanField(default=False, verbose_name='Работа без упоминания в конфе'),
        ),
    ]
