# Generated by Django 5.0.6 on 2024-05-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0016_rename_gpt_key_usersettings_chat_gpt_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='chat_gpt_key',
            field=models.CharField(blank=True, max_length=256, verbose_name='Ключ GPT'),
        ),
    ]
