# Generated by Django 5.0 on 2024-01-28 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0016_profile_gamer2'),
        ('games', '0004_remove_gamer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gamer2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile',
                                       to='games.gamer', verbose_name='Игрок'),
        ),
    ]
