# Generated by Django 5.0.7 on 2024-07-15 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0017_alter_usersettings_chat_gpt_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gamer',
        ),
    ]
