# Generated by Django 5.0 on 2024-01-28 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0017_alter_profile_gamer2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gamer2',
            new_name='gamer',
        ),
    ]
