# Generated by Django 5.1 on 2024-10-02 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0019_alter_usersettings_chat_gpt_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='settings',
        ),
        migrations.AddField(
            model_name='chatsettings',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='settings', to='bot.chat', verbose_name='Чат'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='settings', to='bot.profile', verbose_name='Профиль'),
        ),
    ]
