# Generated by Django 5.1 on 2024-11-10 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0021_alter_chatsettings_chat_alter_usersettings_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSettings',
            new_name='ProfileSettings',
        ),
    ]
