# Generated by Django 5.1.6 on 2025-03-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0024_alter_profilesettings_chat_gpt_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsettings',
            name='time_conversion',
            field=models.BooleanField(default=True, verbose_name='Переводить время в разные часовые пояса'),
        ),
    ]
