# Generated by Django 5.1.6 on 2025-05-04 00:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0027_alter_profilesettings_chat_gpt_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesettings',
            name='chat_gpt_key',
        ),
        migrations.RemoveField(
            model_name='profilesettings',
            name='chat_gpt_model',
        ),
    ]
